/**
 * Action batch "learn-early" — GENERATED by tools/build-content.mjs from actions-learn-early.json.
 *
 * Authored against content/sim/AUTHORING.md by a schema-constrained author, then
 * checked by an adversarial safety verifier (two-tier boundary, capacity-event
 * boundary, never-command five, no-numbers, no-dominant-option, evidence labels,
 * voice) and repaired against its findings, then read in the rolling human review.
 * 9 records. Originally compiled from a JSON batch by tools/build-content.mjs;
 * that JSON was not retained, so THIS FILE is the authored artifact now and is
 * edited directly. Its shape stays JSON-compatible so tools/variant-hygiene.mjs
 * can keep rewriting it structurally.
 */
import type { SimAction } from "@/content/sim/schema";

export const ACTIONS_LEARN_EARLY: SimAction[] = [
  {
    "id": "act-learn-enroll-decision",
    "family": "school",
    "domains": [
      "education",
      "money",
      "identity"
    ],
    "label": "Decide the enrollment question",
    "scene": "The aid packet came. Grants cover part of it; the rest is a loan you sign in a portal on your phone. Down the road there is a community college with no dorms and a transfer agreement. Your manager has already asked about your fall hours.",
    "contract": {
      "costs": {
        "timeStructure": 2,
        "energy": 1
      },
      "reversibility": "costly to undo",
      "switchingCost": "Credits move between schools badly, and the loan does not move at all.",
      "variance": "wide",
      "opportunityNote": "A full-time schedule takes the hours a full-time job would have taken.",
      "evidenceLabel": "contested"
    },
    "options": [
      {
        "id": "opt-enroll-sign-and-go",
        "label": "Sign the loan, go full time",
        "chips": {
          "costs": [
            "a monthly payment that starts whether you finish or not",
            "the hours a full-time wage would have used"
          ],
          "variance": "wide",
          "reversibility": "locks in",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "Nobody covers the gap if a term goes wrong."
            },
            {
              "when": "start:family-backstop",
              "text": "Someone can absorb a bad term, which changes what the loan risks."
            }
          ]
        },
        "sensitivity": {
          "capability": "learning",
          "constraintFlags": [
            "start:no-backstop",
            "start:income-obligation"
          ],
          "systemicFlags": [
            "aid-package"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You land in a program that fits, with a cohort that studies together. The work is hard in the way you wanted it to be hard.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "connection": 1
                },
                "capability": {
                  "learning": 2
                },
                "skills": [
                  "study-habits"
                ],
                "flagsSet": [
                  "enrolled-degree",
                  "carrying-education-debt"
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You are in. The first term is administrative chaos and then it settles. The debt is real and quiet in the background.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "academic-writing"
                ],
                "flagsSet": [
                  "enrolled-degree",
                  "carrying-education-debt"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Two classes are what you came for. The rest is filler you are paying for at exactly the same rate.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "timeStructure": -1
                },
                "capability": {
                  "learning": 1
                },
                "flagsSet": [
                  "enrolled-degree",
                  "carrying-education-debt"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-enroll-community",
        "label": "Start at the community college",
        "chips": {
          "costs": [
            "a route people will underrate out loud",
            "the transfer paperwork is entirely on you"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "systemicFlags": [
            "articulation-agreement"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Cheap credits, a parking lot instead of a campus, and an instructor who used to do the job for a living.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "study-habits"
                ],
                "flagsSet": [
                  "enrolled-two-year"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The classes are fine. Nobody in the building has time to tell you which ones transfer, so you guess.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "learning": 1
                },
                "flagsSet": [
                  "enrolled-two-year",
                  "credits-unverified"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "You take the sequence an adviser recommended. Most of it turns out to be developmental coursework that carries no credit anywhere.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "enrolled-two-year"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-enroll-work-first",
        "label": "Work a year, decide later",
        "chips": {
          "costs": [
            "the year is a year, and you do not get it back",
            "people stop asking what you are studying"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "constraintFlags": [
            "start:income-obligation"
          ],
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You bank a season of wages and watch two people you know leave programs they picked in a hurry.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "adaptability": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The job absorbs you. The question is still open, and quieter than it was in the spring.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "flagsSet": [
                  "deferred-enrollment"
                ]
              }
            }
          }
        ]
      }
    ],
    "failureModes": [
      "signed for a program you leave in the second year",
      "credits that do not transfer anywhere",
      "deferred until the momentum went"
    ],
    "recoveryRefs": [
      "act-learn-exit-program",
      "act-learn-adjacent-entry"
    ],
    "readRef": "/map/credential-decision",
    "seasonBands": [
      [
        1,
        4
      ]
    ]
  },
  {
    "id": "act-learn-apprenticeship-apply",
    "family": "school",
    "domains": [
      "education",
      "work",
      "trades"
    ],
    "label": "Chase the apprenticeship slot",
    "scene": "The local's apprenticeship opens once a year. There is an aptitude test, an interview panel of people who have done the work for decades, and a list far longer than the intake. Someone at the hall tells you he applied twice before he got in.",
    "contract": {
      "costs": {
        "timeStructure": 2,
        "energy": 2
      },
      "reversibility": "reversible",
      "variance": "wide",
      "opportunityNote": "The intake is annual. Missing it costs a year, not a season.",
      "evidenceLabel": "illustrative"
    },
    "options": [
      {
        "id": "opt-apprentice-test",
        "label": "Prep hard and test",
        "chips": {
          "costs": [
            "weeks of arithmetic you have not touched since school",
            "unpaid time off for the test day"
          ],
          "variance": "wide",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:place-bound",
              "text": "The nearest hall running an intake is not near."
            }
          ]
        },
        "sensitivity": {
          "capability": "learning",
          "skill": "study-habits",
          "systemicFlags": [
            "intake-cap"
          ],
          "constraintFlags": [
            "start:place-bound"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "You place high enough to get the call. First-year pay is low, and it is pay, and the classroom hours are on the clock.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": -1
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "trade-fundamentals"
                ],
                "flagsSet": [
                  "apprenticed",
                  "employed"
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You place, below the intake. They keep the list, and next year you start it partway up rather than at the bottom.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "study-habits"
                ],
                "flagsSet": [
                  "apprentice-waitlist"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "You test in the middle of the pack against people who have been on a site since they were sixteen. No feedback, just a ranking.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "adaptability": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-apprentice-helper",
        "label": "Take helper work to get known",
        "chips": {
          "costs": [
            "a body-wearing job at the bottom of the pay scale",
            "no guarantee the sponsorship ever comes"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "companionFlags": [
            "arc-coworker-ray"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You carry material for a crew all season. By the end, two of them know your name and one of them signs things.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                },
                "skills": [
                  "shift-work"
                ],
                "flagsSet": [
                  "employed",
                  "known-at-the-shop"
                ],
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "label": "Ray, on the crew",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The work is the work. Nobody mentions the apprenticeship, and you do not want to be the one who asks every week.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                },
                "skills": [
                  "shift-work"
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "The panel asks what you would do if a job ran long on a Friday. You answer like someone who has already done it. You are in."
      ],
      "solid": [
        "Not this cycle. The coordinator knows your name now, which is more than you had going in.",
        "You end the season nearer the intake than you started it, and outside it."
      ],
      "mixed": [
        "You get on a crew and off it again. Nothing is decided, and you are no longer a stranger at the hall."
      ],
      "poor": [
        "The test day moves and your shift does not. You sit it tired and it shows in the section you were best at."
      ]
    },
    "failureModes": [
      "ranked below the cut with no feedback",
      "the test date landed on a shift you could not drop"
    ],
    "recoveryRefs": [
      "act-learn-adjacent-entry",
      "act-learn-certification-exam",
      "act-learn-practice-block"
    ],
    "readRef": "/topics/work",
    "seasonBands": [
      [
        1,
        8
      ]
    ],
    "repeatable": true
  },
  {
    "id": "act-learn-course-mis-sold",
    "family": "school",
    "domains": [
      "education",
      "money",
      "institutions"
    ],
    "label": "Handle the course that lied",
    "scene": "The site promised a portfolio, an industry mentor and a hiring network. Weeks in, the mentor is a shared inbox, the projects are the free tutorial you already worked through, and the hiring network is a job board anyone can read. You have paid for most of it.",
    "contract": {
      "costs": {
        "timeStructure": 1,
        "energy": 2,
        "money": 1
      },
      "reversibility": "costly to undo",
      "switchingCost": "Refund windows are written to close before a course gets bad enough to notice.",
      "variance": "wide",
      "opportunityNote": "Every week you spend deciding is a week further from the refund window.",
      "evidenceLabel": "illustrative"
    },
    "options": [
      {
        "id": "opt-course-refund",
        "label": "Push for the refund",
        "chips": {
          "costs": [
            "hours inside a complaints process built to tire you out",
            "the one tutor you liked stops answering"
          ],
          "variance": "very wide",
          "reversibility": "reversible"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/topics/money",
        "sensitivity": {
          "capability": "execution",
          "systemicFlags": [
            "refund-window",
            "arbitration-clause"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "You document everything, name the specific promises, and go over the coordinator's head. They offer part of it back to make you go away.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "paperwork"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The terms you agreed to have a clause for exactly this. What you get is credit toward another course from the same people.",
              "effects": {
                "capability": {
                  "execution": 1
                },
                "flagsSet": [
                  "course-credit-held"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The window closed a month before you noticed anything. Everything after that is a form that routes back to the same shared inbox.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "money": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-course-finish",
        "label": "Finish it and mine it",
        "chips": {
          "costs": [
            "more months on something you have already judged",
            "the sunk-cost feeling at the start of every session"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You strip it for the parts that are real: two instructors who answer properly, and a cohort chat that outlives the course.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "self-teaching"
                ],
                "flagsSet": [
                  "completed-course"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You finish. The certificate goes on the profile, and nobody in an interview has heard of the school.",
              "effects": {
                "gauge": {
                  "timeStructure": -1,
                  "healthEnergy": -1
                },
                "capability": {
                  "execution": 1
                },
                "flagsSet": [
                  "completed-course"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-course-walk",
        "label": "Stop going, keep the time",
        "chips": {
          "costs": [
            "the money is gone whatever you do now",
            "another unfinished thing on the list of unfinished things"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You cut it the same week you decide, and put the evenings into building the thing the course was supposed to teach you to build.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "capability": {
                  "adaptability": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You stop. The money stays spent, the evenings come back, and it sits with you for a while.",
              "effects": {
                "gauge": {
                  "timeStructure": 1,
                  "healthEnergy": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-course-report",
        "label": "Report it and warn people",
        "chips": {
          "costs": [
            "a process that helps the next cohort rather than you",
            "your name on the complaint if the school asks who filed it"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "systemicFlags": [
            "state-licensing-board"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You file with the board that licenses them and write the review you wanted to read before you paid. Two people message you to say they backed out.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "healthEnergy": -1
                },
                "capability": {
                  "regulation": 1
                },
                "skills": [
                  "paperwork"
                ],
                "flagsSet": [
                  "filed-complaint"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The board acknowledges receipt. The school's reply calls it a misunderstanding, names you in it, and the whole thing joins a queue somewhere.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "regulation": 1
                },
                "flagsSet": [
                  "filed-complaint"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "The school answers your review under your full name, and posts four of its own above it. Nothing is decided. You stop opening the thread.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "connection": -1
                },
                "flagsSet": [
                  "filed-complaint"
                ]
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-learn-refund-lands",
        "label": "The partial refund clears, long after you stopped expecting it.",
        "effects": {
          "gauge": {
            "money": 1
          }
        },
        "due": {
          "seasons": 3
        },
        "onBands": [
          "strong"
        ]
      }
    ],
    "failureModes": [
      "the refund window closed before the problem was obvious",
      "you finished it and nobody hiring had heard of the school"
    ],
    "recoveryRefs": [
      "act-learn-practice-block",
      "act-learn-certification-exam"
    ],
    "readRef": "/topics/money",
    "seasonBands": [
      [
        2,
        10
      ]
    ]
  },
  {
    "id": "act-learn-practice-block",
    "family": "school",
    "domains": [
      "education",
      "mastery",
      "habits"
    ],
    "label": "Protect a practice block",
    "scene": "Nobody is grading this. The same evenings every week, on the one skill you would have to be genuinely good at to get where you said you were going. The hard part is that nothing happens if you skip it.",
    "contract": {
      "costs": {
        "timeStructure": 2,
        "energy": 1,
        "money": 1
      },
      "reversibility": "reversible",
      "variance": "moderate",
      "opportunityNote": "The hours come out of the evenings you currently spend recovering.",
      "evidenceLabel": "evidence-informed"
    },
    "options": [
      {
        "id": "opt-practice-alone",
        "label": "Work alone on hard things",
        "chips": {
          "costs": [
            "nobody tells you when you are drilling the wrong thing",
            "the money goes on materials rather than on a teacher"
          ],
          "variance": "moderate",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:caring-duty",
              "text": "Your evenings already belong to someone who cannot reschedule."
            }
          ]
        },
        "sensitivity": {
          "capability": "execution",
          "gauge": "timeStructure",
          "constraintFlags": [
            "start:caring-duty",
            "start:income-obligation"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "The evenings hold. By the end of the season, work that used to take a whole sitting takes part of one.",
              "effects": {
                "capability": {
                  "learning": 1,
                  "execution": 1
                },
                "skills": [
                  "deliberate-practice"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Some weeks hold, some do not. You are better than you were, and not by as much as the hours suggest.",
              "effects": {
                "capability": {
                  "learning": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "The block is the first thing that moves when a shift moves. By midseason there is no block, only an intention.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-practice-coached",
        "label": "Pay someone better than you",
        "chips": {
          "costs": [
            "a standing bill for something with no certificate at the end",
            "being watched while you are bad at it"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "gauge": "money",
          "capability": "learning",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "They watch you work and name, inside one session, the thing you have been doing wrong for a year.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "learning": 2
                },
                "skills": [
                  "deliberate-practice"
                ],
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "label": "Okonkwo, who teaches",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The feedback is worth what it costs, and the bill is still a bill. You stop rehearsing your own errors.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "deliberate-practice"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "They are good at the thing and not at teaching it. You get some of it by watching them do it.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "learning": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-practice-group",
        "label": "Join people who meet weekly",
        "chips": {
          "costs": [
            "the group's pace, which is not your pace",
            "a night that now belongs to other people"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "companionFlags": [
            "group-holds"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "The group meets whether you feel like it or not. You go on the nights you would have skipped alone.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "learning": 1,
                  "execution": 1
                },
                "skills": [
                  "deliberate-practice"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Half the group is there to talk. You get a night out and a modest amount of practice.",
              "effects": {
                "gauge": {
                  "connection": 1
                }
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "Someone who does this for a living takes your work apart in front of you. It is uncomfortable and it is the fastest season you have had."
      ],
      "solid": [
        "You keep the block through a bad month. Nothing dramatic changes; the floor under the skill moves up.",
        "The season ends with a piece of work you would show somebody, which was not true in the spring."
      ],
      "mixed": [
        "You put in the time and spend most of it on the parts you already enjoy.",
        "The block survives the season, and the hard part of the skill is where you left it."
      ],
      "poor": [
        "You drill the same thing all season, well, and it is the wrong thing to have been drilling."
      ]
    },
    "failureModes": [
      "the block was the first thing cut when a shift moved",
      "practice without feedback rehearsed the mistake"
    ],
    "recoveryRefs": [
      "act-learn-study-alongside-work"
    ],
    "readRef": "/guidance",
    "seasonBands": [
      [
        1,
        12
      ]
    ],
    "repeatable": true,
    "standing": {
      "seasons": 3,
      "upkeep": {
        "timeStructure": 1
      }
    }
  },
  {
    "id": "act-learn-first-real-project",
    "family": "work",
    "domains": [
      "education",
      "work",
      "portfolio"
    ],
    "label": "Build the first real thing",
    "scene": "Practice exercises have the answer at the back. This does not: a real job for a real person with opinions, a deadline that belongs to somebody else, and a scope that will move once you start. Lu's shop needs it done. She is not paying much.",
    "contract": {
      "costs": {
        "timeStructure": 2,
        "energy": 2
      },
      "reversibility": "reversible",
      "variance": "wide",
      "opportunityNote": "A season on one deliverable is a season not spent getting broader.",
      "evidenceLabel": "evidence-informed"
    },
    "options": [
      {
        "id": "opt-project-paid-small",
        "label": "Take the small paid job",
        "chips": {
          "costs": [
            "a client with opinions and a budget of almost nothing",
            "you give up the right to walk away once you have taken money"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "execution",
          "skill": "deliberate-practice",
          "companionFlags": [
            "arc-neighbor-lu"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "It ships. It is not perfect and it is out in the world with her name on it, which is a different category of thing from anything in your folder.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "connection": 1
                },
                "capability": {
                  "execution": 2
                },
                "skills": [
                  "client-work"
                ],
                "flagsSet": [
                  "has-shipped-work"
                ],
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "label": "Lu, from the shop",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Late, and delivered. She is pleased enough to say so to somebody else.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "client-work"
                ],
                "flagsSet": [
                  "has-shipped-work"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The scope moved every time you showed her something. The deadline arrives with a thing that is nearly finished, which is not a thing.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "connection": -1
                },
                "capability": {
                  "adaptability": 1
                },
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "label": "Lu, from the shop",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-project-own",
        "label": "Build your own thing properly",
        "chips": {
          "costs": [
            "no deadline anybody else enforces",
            "nobody asked for it, and nobody is waiting for it"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You finish it because you said you would. It is the best thing you have made, and you control every frame of how it is shown.",
              "effects": {
                "capability": {
                  "execution": 1,
                  "learning": 1
                },
                "skills": [
                  "deliberate-practice"
                ],
                "flagsSet": [
                  "has-shipped-work"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "It reaches the point where it works and stops there. Good enough to show, not finished enough to be proud of.",
              "effects": {
                "capability": {
                  "learning": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-project-volunteer",
        "label": "Do it free for a nonprofit",
        "chips": {
          "costs": [
            "work with no money attached, for people who will ask again",
            "a committee that meets once a month and decides slowly"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "systemicFlags": [
            "board-approval"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "A name people recognize goes on the work, and the coordinator writes you something you can actually use.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "skills": [
                  "client-work"
                ],
                "flagsSet": [
                  "has-shipped-work",
                  "has-reference"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Months of waiting on other people's approvals for something that ends up small. The logo on it is worth more than the work.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "timeStructure": -1
                }
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "You hand it over early. She uses it in front of you and asks what else you can do."
      ],
      "solid": [
        "You finish it because you said you would. It is the best thing you have made.",
        "It goes out late and it goes out. Somebody who did not have to say anything says it was good.",
        "It is done, and there is a version of it you can show a stranger without explaining what it was meant to be."
      ],
      "mixed": [
        "The season goes into it, and what comes out is smaller than the season.",
        "It is finished in the sense that you have stopped working on it."
      ],
      "poor": [
        "You take the notes personally, rewrite it twice, and hand over something worse than the first version."
      ]
    },
    "delayedEffects": [
      {
        "id": "de-learn-project-referral",
        "label": "Somebody who saw the finished work asks whether you take jobs.",
        "effects": {
          "gauge": {
            "money": 1,
            "connection": 1
          },
          "flagsSet": [
            "has-referral"
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "strong",
          "solid"
        ]
      }
    ],
    "failureModes": [
      "scope moved until the deadline was gone",
      "you built it well and cannot show it to anyone"
    ],
    "recoveryRefs": [
      "act-learn-practice-block",
      "act-learn-adjacent-entry"
    ],
    "readRef": "/topics/work",
    "seasonBands": [
      [
        3,
        12
      ]
    ],
    "repeatable": true
  },
  {
    "id": "act-learn-certification-exam",
    "family": "civic",
    "domains": [
      "education",
      "credential",
      "work"
    ],
    "label": "Sit the certification exam",
    "scene": "The exam costs about a week's take-home pay, and the retake costs the same again. The material is partly the job and partly the exam board's idea of the job. The postings you want list it as required. The people already doing the work are split on whether it changed anything.",
    "contract": {
      "costs": {
        "timeStructure": 2,
        "energy": 1
      },
      "reversibility": "reversible",
      "variance": "wide",
      "opportunityNote": "The fee is the fee whether you pass or not.",
      "evidenceLabel": "contested"
    },
    "options": [
      {
        "id": "opt-cert-prep-hard",
        "label": "Book it and prepare properly",
        "chips": {
          "costs": [
            "the fee, and the fee again if it goes badly",
            "a season of evenings on exam-shaped material rather than the work itself"
          ],
          "variance": "wide",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "A failed sitting is a month of groceries you will not get back."
            }
          ]
        },
        "sensitivity": {
          "capability": "learning",
          "skill": "study-habits",
          "gauge": "money",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You pass comfortably. Within a season a recruiter contacts you about a posting that filtered on exactly that line.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "exam-technique"
                ],
                "flagsSet": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You pass. The letters go on the profile. Your current employer notices and does not pay you differently for it.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "capability": {
                  "learning": 1
                },
                "flagsSet": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "You miss the cut. The report gives a band and no detail, and the retake fee is the full fee.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "healthEnergy": -1
                },
                "capability": {
                  "regulation": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-cert-sit-cold",
        "label": "Sit it cold and see",
        "chips": {
          "costs": [
            "a fee spent on reconnaissance",
            "some boards keep a failed attempt on the record"
          ],
          "variance": "very wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "adaptability",
          "skill": "shift-work",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 1,
            "outcome": {
              "line": "You pass on the strength of the job you already do. The prep everyone insisted on was for somebody else.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "flagsSet": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You do not pass, and you come out knowing exactly what the exam wants, which is what you paid for.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "capability": {
                  "adaptability": 1
                },
                "skills": [
                  "exam-technique"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-cert-ask-employer",
        "label": "Ask the employer to fund it",
        "chips": {
          "costs": [
            "a conversation that marks you as somebody with plans",
            "a clawback clause if you leave before the term is up"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "systemicFlags": [
            "employer-tuition-policy"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "They agree to fund it, on the condition that you stay a set number of seasons afterwards. You sign, and you pass.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "training-bond",
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "There is a policy, and the budget for it went early in the year. You put the fee on your own card, sit it late in the season, and come away with a retake date.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "capability": {
                  "socialNavigation": 1
                },
                "skills": [
                  "exam-technique"
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "You pass, and the letters after your name get you past the screen that had been quietly discarding you."
      ],
      "solid": [
        "You pass. The letters go on the profile, and your employer notices without paying you differently for it.",
        "It lands. The certificate arrives weeks later, by which time you have already told the people you wanted to tell.",
        "You pass, and the Monday after is exactly the Monday it was going to be."
      ],
      "mixed": [
        "You sit it at the end of a long week. What comes back is a band and a retake date, and the fee is spent either way.",
        "No certificate this season. What you have instead is a precise map of what stands between you and it."
      ],
      "poor": [
        "You sit it on the back of a double shift and lose the section you had been strongest in."
      ]
    },
    "failureModes": [
      "missed the cut by a margin they will not disclose",
      "passed, and nothing about the job or the pay changed"
    ],
    "recoveryRefs": [
      "act-learn-practice-block",
      "act-learn-adjacent-entry"
    ],
    "readRef": "/map/credential-decision",
    "seasonBands": [
      [
        2,
        12
      ]
    ],
    "repeatable": true
  },
  {
    "id": "act-learn-exit-program",
    "family": "threshold",
    "domains": [
      "education",
      "institutions",
      "money"
    ],
    "label": "Leave the program cleanly",
    "scene": "You are not going back. The question is what happens in the next month: a withdrawal form and an adviser meeting, a transfer packet to somewhere cheaper, or nothing at all, which the registrar will read as failing every class you are still enrolled in.",
    "contract": {
      "costs": {
        "timeStructure": 1,
        "energy": 2
      },
      "reversibility": "locks in",
      "switchingCost": "Coming back later means reapplying, with a transcript that shows how you left.",
      "variance": "wide",
      "opportunityNote": "Leaving mid-term forfeits the term's money and the term's credits together.",
      "evidenceLabel": "evidence-informed"
    },
    "options": [
      {
        "id": "opt-exit-formal",
        "label": "Withdraw on the record",
        "chips": {
          "costs": [
            "an adviser meeting where you explain yourself out loud",
            "a month of appointments before any of the hours come back",
            "the partial-refund deadline is close and nobody will remind you"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "execution",
          "systemicFlags": [
            "withdrawal-deadline"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Forms, signatures, a date stamped before the deadline. The transcript shows withdrawals rather than failures, and part of the term's money comes back in the spring.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "paperwork"
                ],
                "flagsSet": [
                  "left-cleanly"
                ],
                "flagsClear": [
                  "enrolled-degree",
                  "enrolled-two-year"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You get it filed. The refund window had already closed, and the servicer starts counting from the day you stopped being enrolled.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "left-cleanly",
                  "carrying-education-debt"
                ],
                "flagsClear": [
                  "enrolled-degree",
                  "enrolled-two-year"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-exit-transfer",
        "label": "Move the credits somewhere cheaper",
        "chips": {
          "costs": [
            "a term of limbo while an office evaluates your transcript",
            "some of what you already did will not survive the move"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "systemicFlags": [
            "articulation-agreement"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "There is an agreement between the two schools and most of what you did counts. You start partway in, paying less per credit.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "enrolled-two-year",
                  "transferred"
                ],
                "flagsClear": [
                  "enrolled-degree"
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The general requirements move across. The ones in your subject do not, and you repeat a year of them at the cheaper rate.",
              "effects": {
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "enrolled-two-year",
                  "transferred"
                ],
                "flagsClear": [
                  "enrolled-degree"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The evaluation takes the whole season. You are enrolled nowhere in the meantime, and the servicer notices before the new school does.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "transfer-pending"
                ],
                "flagsClear": [
                  "enrolled-degree"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-exit-drift",
        "label": "Stop going and say nothing",
        "chips": {
          "costs": [
            "the term's grades get decided in your absence",
            "a transcript you will explain to every school after this one"
          ],
          "variance": "wide",
          "reversibility": "locks in",
          "positionNotes": [
            {
              "when": "start:income-obligation",
              "text": "The hours you free up this week are hours somebody at home is counting on."
            },
            {
              "when": "start:no-backstop",
              "text": "Nothing behind you covers a balance the school decides you still owe."
            }
          ]
        },
        "sensitivity": {
          "capability": "regulation",
          "systemicFlags": [
            "withdrawal-deadline"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The season is yours the week you decide. You pick up full-time hours in time for the next check and stop thinking about the building.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": 2,
                  "healthEnergy": 1
                },
                "flagsSet": [
                  "unofficial-withdrawal"
                ],
                "flagsClear": [
                  "enrolled-degree"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 3,
            "failure": true,
            "outcome": {
              "line": "The term posts as failures rather than withdrawals. Aid eligibility goes with it, and the balance for a term you did not attend is still owed.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "capability": {
                  "regulation": -1
                },
                "flagsSet": [
                  "unofficial-withdrawal",
                  "carrying-education-debt",
                  "aid-suspended"
                ],
                "flagsClear": [
                  "enrolled-degree"
                ]
              }
            }
          }
        ]
      }
    ],
    "failureModes": [
      "an unofficial withdrawal recorded as failure across the whole term",
      "the debt stayed and the credits did not"
    ],
    "recoveryRefs": [
      "act-learn-adjacent-entry",
      "act-learn-practice-block"
    ],
    "readRef": "/map/credential-decision",
    "seasonBands": [
      [
        2,
        12
      ]
    ]
  },
  {
    "id": "act-learn-study-alongside-work",
    "family": "school",
    "domains": [
      "education",
      "work",
      "capacity"
    ],
    "label": "Study through a work season",
    "scene": "The class meets on evenings you are usually scheduled. Your manager will move the schedule if you ask, and asking marks you as somebody with one foot out the door. The alternative is the online section, which is the same material taught to nobody in particular.",
    "contract": {
      "costs": {
        "timeStructure": 3,
        "energy": 2
      },
      "reversibility": "reversible",
      "variance": "moderate",
      "opportunityNote": "The season has room for the class or for picking up hours, not for both.",
      "evidenceLabel": "evidence-informed"
    },
    "options": [
      {
        "id": "opt-study-ask-schedule",
        "label": "Ask for the schedule you need",
        "chips": {
          "costs": [
            "being visibly somebody with plans elsewhere",
            "the shifts you get moved onto are the ones nobody wanted"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "companionFlags": [
            "arc-coworker-ray"
          ],
          "systemicFlags": [
            "scheduling-policy"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "The manager rearranges it and mentions she did the same thing at your age. You get the evenings, and a slightly different standing at work.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "capability": {
                  "learning": 1,
                  "socialNavigation": 1
                },
                "skills": [
                  "study-habits"
                ],
                "flagsSet": [
                  "schedule-accommodated"
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She moves you to opens. You make every class, and you are awake for none of the mornings.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "study-habits",
                  "pacing"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You get the evenings for part of the season. After that the schedule goes back to whatever suits the store.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "timeStructure": -1
                },
                "capability": {
                  "learning": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-study-online",
        "label": "Take the online section",
        "chips": {
          "costs": [
            "a course with nobody else visibly in it",
            "no instructor who will remember your name for a reference"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "skill": "self-teaching",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "It fits around the shifts, because it fits around anything. You finish it, alone, at hours that suit nobody.",
              "effects": {
                "capability": {
                  "learning": 1,
                  "execution": 1
                },
                "skills": [
                  "self-teaching"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You keep up until the season gets busy, and then it becomes a thing you are behind on rather than a thing you are doing.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "learning": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "Nothing about the format made you show up, and nothing about it noticed when you stopped.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": -1
                },
                "capability": {
                  "regulation": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-study-cut-hours",
        "label": "Cut hours to make room",
        "chips": {
          "costs": [
            "a smaller check every two weeks, starting immediately",
            "the hours go onto somebody else's schedule, and getting them back means asking twice"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "Nothing behind you absorbs the difference between the two checks."
            }
          ]
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:income-obligation",
            "start:no-backstop"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You go part time and do the class properly. The money is tight in a way you feel weekly, and the work is the best you have done.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "learning": 2
                },
                "skills": [
                  "study-habits"
                ],
                "flagsSet": [
                  "part-time-hours"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You cut the hours, and the class expands to fill more than the space you made for it.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "learning": 1
                }
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "Two people on your shift want the same class. Between you, the schedule covers itself."
      ],
      "solid": [
        "You make the classes, most weeks, and the work you hand in is work you would put your name on.",
        "The season holds. You are tired in the specific way of somebody doing two things, and both of them get done.",
        "You finish the term. None of the arrangement was comfortable and none of it fell over."
      ],
      "mixed": [
        "You finish the term with the material half in you. What you have is a pass and a gap you will find later.",
        "The arrangement holds for part of the season and then stops holding. You get through on what you already knew."
      ],
      "poor": [
        "The term ends without you. You never decide to stop; you just do not open it again after a bad two weeks."
      ]
    },
    "failureModes": [
      "the schedule changed after the add-drop date",
      "you passed the class and slept through the season"
    ],
    "recoveryRefs": [
      "act-learn-practice-block",
      "act-learn-certification-exam"
    ],
    "readRef": "/topics/work",
    "seasonBands": [
      [
        1,
        12
      ]
    ],
    "repeatable": true,
    "standing": {
      "seasons": 2,
      "upkeep": {
        "timeStructure": 1,
        "energy": 1
      }
    }
  },
  {
    "id": "act-learn-adjacent-entry",
    "family": "work",
    "domains": [
      "work",
      "education",
      "access"
    ],
    "label": "Get in at the bottom instead",
    "scene": "The clinic needs somebody on the front desk. The pay is what it is, the work is scheduling and insurance forms, and the people doing the job you actually want walk past you all day. Nobody there will teach you anything unless you ask well.",
    "contract": {
      "costs": {
        "timeStructure": 2,
        "energy": 2
      },
      "reversibility": "reversible",
      "switchingCost": "A year at the desk reads as front-desk experience unless you make it read as something else.",
      "variance": "wide",
      "opportunityNote": "Time inside the building is time not spent on the credential that gets you in the door elsewhere.",
      "evidenceLabel": "contested"
    },
    "options": [
      {
        "id": "opt-entry-take-desk",
        "label": "Take the desk job",
        "chips": {
          "costs": [
            "a job title that follows you into the next application",
            "the work is not the work you came for"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "systemicFlags": [
            "internal-hiring-policy"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "You learn the whole building: who decides what, which forms matter, what the job actually is. When an internal posting opens, you are the known quantity.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 2
                },
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "employed",
                  "inside-the-building"
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Steady pay, a badge, and a slow map of how the place works. The job you wanted is still behind a requirement you do not meet.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "employed",
                  "inside-the-building"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "A season in, you are very good at the desk. Being very good at the desk is the reason they will not move you off it.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "employed",
                  "typecast-at-work"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-entry-ask-shadow",
        "label": "Take it and ask to shadow",
        "chips": {
          "costs": [
            "asking for unpaid extra on top of a full shift",
            "some people will say no, and will remember that you asked"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "companionFlags": [
            "arc-mentor-okonkwo"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "One of them lets you sit in on a morning a week. It is unpaid, it is tiring, and it is the closest thing to training anyone has offered you.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "connection": 1
                },
                "capability": {
                  "learning": 2,
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "employed",
                  "inside-the-building"
                ],
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "label": "Okonkwo, who lets you watch",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Everyone says yes in principle and nobody has a morning. It stays a thing that is going to get scheduled.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "employed",
                  "inside-the-building"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-entry-hold-out",
        "label": "Hold out for the actual role",
        "chips": {
          "costs": [
            "a longer stretch with no income from the field at all",
            "the openings you are holding out for want experience you are not getting"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:no-backstop"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You keep the season clear and put it into the qualification the postings actually name. Your position does not improve; your application does.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "study-habits"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You wait for the role and apply to the ones that appear. The gap on the record grows by a season either way.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "adaptability": 1
                }
              }
            }
          }
        ]
      }
    ],
    "failureModes": [
      "a year in, still the person who answers the phone",
      "the informal training everyone promised never got scheduled"
    ],
    "recoveryRefs": [
      "act-learn-certification-exam",
      "act-learn-practice-block",
      "act-learn-apprenticeship-apply"
    ],
    "readRef": "/topics/work",
    "seasonBands": [
      [
        1,
        10
      ]
    ]
  }
];
