/**
 * Event batch "comp-work" — GENERATED by tools/build-content.mjs from events-comp-work.json.
 *
 * Authored against content/sim/AUTHORING.md by a schema-constrained author, then
 * checked by an adversarial safety verifier (two-tier boundary, capacity-event
 * boundary, never-command five, no-numbers, no-dominant-option, evidence labels,
 * voice) and repaired against its findings, then read in the rolling human review.
 * 12 records. Originally compiled from a JSON batch by tools/build-content.mjs;
 * that JSON was not retained, so THIS FILE is the authored artifact now and is
 * edited directly. Its shape stays JSON-compatible so tools/variant-hygiene.mjs
 * can keep rewriting it structurally.
 */
import type { SimEvent } from "@/content/sim/schema";

export const EVENTS_COMP_WORK: SimEvent[] = [
  {
    "id": "evt-ray-shift-swap",
    "family": "work",
    "domains": [
      "work",
      "people",
      "reliability"
    ],
    "label": "Ray asks for the close",
    "scene": "Ray catches you by the lockers before the shift. Ray's sister has a thing on Saturday and the close needs covering. No case gets made for it, no favour gets called in. Ray just asks, which is not something Ray does often.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-coworker-ray"
    },
    "seasonBands": [
      [
        1,
        20
      ]
    ],
    "options": [
      {
        "id": "opt-ray-take-close",
        "label": "Take the close",
        "chips": {
          "costs": [
            "your Saturday night",
            "a shift's worth of energy"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You work it. Ray checks the till count twice out of habit, finds it right, and stops checking. On Monday the good mid-shift has your name against it.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "ray-trusts-your-shift"
                ],
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The close runs long and the delivery paperwork goes wrong somewhere in the last hour. Ray sorts it on Monday without comment and does not raise it again.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-offer-sunday",
        "label": "Offer the Sunday instead",
        "chips": {
          "costs": [
            "a Sunday you were keeping",
            "the awkwardness of a counter-offer"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Ray takes the Sunday and finds someone else for Saturday. It costs a phone call neither of you enjoys, and the schedule holds.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Sunday is no use to Ray. The Saturday goes to whoever the manager can find, and the subject closes there.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-ray-say-no",
        "label": "Say no, keep Saturday",
        "chips": {
          "costs": [
            "the corridor conversation gets shorter for a while"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You keep the night. Ray says no problem and means the words, and the rest of the shift is about delivery times.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Ray covers it alone and is fine about it. The asking, which was the new part, does not happen again this season.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "You work it clean. The till is right, the paperwork is right, and on Monday nobody has to fix anything.",
        "The close goes fine. Ray comes in early on Monday out of habit, looks at the sheets, and does not need to."
      ],
      "mixed": [
        "The night runs long and the last hour is a mess that Monday inherits.",
        "It gets done. Not well, not badly. Done."
      ]
    },
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-ray-cools",
    "family": "work",
    "domains": [
      "work",
      "people"
    ],
    "label": "The schedule changes quietly",
    "scene": "The schedule goes up and you are on mid-weeks, all of them. Ray built it and is perfectly civil about it in the corridor. The shifts you were late for do not come up. Neither do the closes you used to get.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-coworker-ray"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-ray-ask-straight",
        "label": "Ask Ray straight out",
        "chips": {
          "costs": [
            "saying the thing out loud in a corridor"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Ray tells you, flatly and without heat, which two shifts it was about. Nothing gets decided in a corridor, but the thing is now said out loud.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Ray keeps it to the schedule. Staffing, cover, the delivery window. You get a straight answer to a question you did not ask.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-work-midweeks",
        "label": "Work the mid-weeks well",
        "chips": {
          "costs": [
            "a season of shifts nobody wants"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You are on time for all of them. Nothing is said. By the end of the season the closes start appearing against your name again, one at a time.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You work them properly. The schedule stays as it is. Whatever changed is not going to be changed back by one season of turning up.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-leave-it",
        "label": "Leave it where it is",
        "chips": {
          "costs": [
            "the mid-weeks, and no conversation"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The schedule is the schedule. You work the middle of the week and go home, and for the first time in a year the weekends are yours.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The mid-weeks stay yours. Somewhere in the season Ray stops asking whether you want the extra hours and starts asking someone else.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-ray-hours-thin",
        "label": "The extra hours go elsewhere",
        "effects": {
          "gauge": {
            "money": -1
          }
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "poor"
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "recoveryRefs": [
      "act-small-ask-one-question",
      "act-small-check-the-numbers"
    ],
    "negative": true
  },
  {
    "id": "evt-ray-repair",
    "family": "work",
    "domains": [
      "work",
      "people",
      "repair"
    ],
    "label": "Putting it right with Ray",
    "scene": "You picked up the two shifts nobody wanted, and you said you would before you did it, which is the part Ray notices. Tuesday, stock room. Ray is counting cases and has not looked up.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-coworker-ray"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-ray-say-once",
        "label": "Say it once, plainly",
        "chips": {
          "costs": [
            "the discomfort of saying it out loud"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "companionFlags": [
            "ray-trusts-your-shift"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Ray hears it, says right, and goes back to the cases. On Thursday you are on the close again. Nothing else about it is ever mentioned.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Ray takes the point without taking it further. Noted, and back to the count. What it changes is not a thing Ray settles in a stock room.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-let-work-say",
        "label": "Let the schedule say it",
        "chips": {
          "costs": [
            "a season of clean shifts and no conversation"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Three months of turning up early and leaving the till right. Late in the season Ray asks you to cover something, which is how Ray says it.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You work it clean all season. Ray works alongside you all season. Neither of you says anything about it, and the season ends where it started.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-explain",
        "label": "Explain the whole thing",
        "chips": {
          "costs": [
            "more of Ray's shift than Ray has"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Ray listens to about half of it, then says the thing about not mixing work and the rest of life, and puts a case on the shelf.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "It comes out as the reasons rather than the thing itself. Ray is polite about it. The count goes on and the subject does not get another run.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative"
  },
  {
    "id": "evt-ray-refuses",
    "family": "work",
    "domains": [
      "work",
      "people",
      "boundaries"
    ],
    "label": "Ray will not swap it",
    "scene": "You need the Friday. Ray is the only one who could take it, and hears the whole thing out before answering. No. Not softened, not explained. Take it to the manager, Ray says, that is what the manager is there for.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-coworker-ray"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-ray-manager",
        "label": "Take it to the manager",
        "chips": {
          "costs": [
            "a form, and a week of not knowing"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "systemicFlags": [
            "short-staffed"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The manager moves someone across from the other site. It takes a week and two emails and the Friday comes free. Ray's answer stays what it was.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The request goes in and comes back declined, on staffing. You work the Friday. Put it in earlier next time, the manager says, not unkindly.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-ray-work-it",
        "label": "Work the Friday",
        "chips": {
          "costs": [
            "whatever the Friday was for"
          ],
          "variance": "narrow",
          "reversibility": "costly to undo"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You work it. The thing the Friday was for gets moved, or gets missed, and the shift is uneventful in the way shifts are.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "connection": -1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You work it thinking about the other thing the whole way through. The till is out at the end and you stay late fixing it.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-push",
        "label": "Ask Ray again",
        "chips": {
          "costs": [
            "asking twice for the same thing"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Ray gives you the same answer in the same words, which is how Ray ends things. The Friday is still yours to work.",
              "effects": {}
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "The second ask lands worse than the first. Ray goes back to being exactly as professional as the job requires and stays there a while.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Ray declining the swap is Ray's decision, not a setback to route out of. The only thing on this card that needs a way on is the Friday itself, and the card already carries that as an option the player chooses rather than as a rescue offered afterwards. A recovery list rendered under a colleague's no would treat the no as a problem to be solved."
    }
  },
  {
    "id": "evt-ray-reference",
    "family": "work",
    "domains": [
      "work",
      "people",
      "advancement"
    ],
    "label": "Ray puts your name in",
    "scene": "There is an opening on the day team and your name is already against it. Ray tells you after, not before. Whatever you do about the interview, Ray says, do not be late for it.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-coworker-ray"
    },
    "seasonBands": [
      [
        5,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-ray-take-interview",
        "label": "Sit the interview",
        "chips": {
          "costs": [
            "a day off the schedule",
            "the nerve it takes"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "companionFlags": [
            "ray-trusts-your-shift"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You get it. Days, a schedule you can plan around, and a small step in what the hour is worth. Ray's name did the part your application could not.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": 1
                },
                "skills": [
                  "shift-work"
                ],
                "flagsSet": [
                  "day-team"
                ],
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "It goes to someone with more time in the building. The manager keeps your name for the next one, and now knows what it is attached to.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The interview does not go well. Ray does not ask how it went, which is a kindness, and the schedule stays exactly as it was.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-ray-decline",
        "label": "Thank Ray, stay put",
        "chips": {
          "costs": [
            "a door that was open this season"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You keep the hours the rest of your life is arranged around. Ray says fair enough and means it, and puts nobody's name anywhere for a while.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You stay. Inside a month the person who took it is training on equipment you already know how to use.",
              "effects": {
                "gauge": {
                  "connection": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-ask-how",
        "label": "Ask Ray how to play it",
        "chips": {
          "costs": [
            "asking, which Ray is not used to",
            "an evening of the shift talking"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Ray tells you what the manager actually asks, and what to say about the till count. You go in knowing the room. The day team starts you in the autumn.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": 1
                },
                "skills": [
                  "shift-work"
                ],
                "flagsSet": [
                  "day-team"
                ],
                "relationships": [
                  {
                    "id": "arc-coworker-ray",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Turn up on time and be straight with them, Ray says, and that is the whole of it. You sit the interview and it goes to the other candidate.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                }
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-day-team-hours",
        "label": "The day-team hours settle in",
        "effects": {
          "gauge": {
            "timeStructure": 1,
            "healthEnergy": 1
          }
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "strong"
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative"
  },
  {
    "id": "evt-ray-leaves",
    "family": "work",
    "domains": [
      "work",
      "people",
      "endings"
    ],
    "label": "Ray's last shift",
    "scene": "Ray tells you on Monday, in the same voice Ray uses for delivery times: last shift Thursday, better hours across town. The locker gets cleared at the end of the week. On Friday somebody else is training the new starter, badly.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-coworker-ray"
    },
    "seasonBands": [
      [
        10,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-ray-drink",
        "label": "Buy Ray a drink",
        "chips": {
          "costs": [
            "an evening, and the money for it"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "One hour in the place by the bus stop. Ray talks about the new job, you both say keep in touch, and you both know roughly what that is worth.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Half the shift turns up and it becomes everyone's night rather than Ray's. You get about four minutes at the end, and they are fine.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-ask-reference",
        "label": "Ask for a reference first",
        "chips": {
          "costs": [
            "asking for something on the way out"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "companionFlags": [
            "ray-trusts-your-shift"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Ray writes it that week. Short, specific, and about the work. It sits in your file and outlasts the thing it came out of.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "flagsSet": [
                  "has-reference"
                ],
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Use the name, Ray says, and gives you a number to pass on. Whether anyone ever calls it is out of your hands and out of Ray's.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-let-it-end",
        "label": "Let the week end",
        "chips": {
          "costs": [
            "a thing you do not say"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Thursday finishes the way any Thursday does. Ray says see you, out of habit, and the back door does its slow close behind the both of you.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The building carries on. For a month you keep expecting the schedule to have Ray on it, and then you stop expecting that.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "capability": {
                  "adaptability": 1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Ray is leaving for better hours, which is a good move for Ray. Nothing on this card went wrong, so there is nothing to be recovered from, and offering the character a way on from it would frame someone else's decision as damage done to them."
    },
    "negative": true
  },
  {
    "id": "evt-okonkwo-office-hours",
    "family": "school",
    "domains": [
      "learning",
      "people",
      "credential"
    ],
    "label": "Tuesday office hours",
    "scene": "Two hours on a Tuesday and a queue down the corridor. She has read your draft. In the margin: this paragraph is doing the work of three, and the other three know it. You get fifteen minutes and she ends it at fifteen.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-mentor-okonkwo"
    },
    "seasonBands": [
      [
        1,
        14
      ]
    ],
    "options": [
      {
        "id": "opt-okonkwo-specific",
        "label": "Bring one specific question",
        "chips": {
          "costs": [
            "the evening it took to earn the question"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "learning",
          "skill": "academic-writing",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "She answers it, then answers the question behind it, then names the two readings that would have got you there alone. The fifteen minutes are worth a term.",
              "effects": {
                "capability": {
                  "learning": 2
                },
                "skills": [
                  "academic-writing"
                ],
                "flagsSet": [
                  "okonkwo-knows-your-work"
                ],
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "She answers it in four sentences and sends you back to the paragraph, with the name of one reading written across the top of it.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "academic-writing"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-ask-field",
        "label": "Ask about the field",
        "chips": {
          "costs": [
            "the fifteen minutes, spent on the long view"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She tells you what the work is actually like, including the parts nobody advertises, and how long the first three years of it took her.",
              "effects": {
                "capability": {
                  "adaptability": 1
                },
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You get the general version. She glances at the clock somewhere around the twelve-minute mark, and the queue is still there when you leave.",
              "effects": {
                "capability": {
                  "adaptability": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-ask-more",
        "label": "Ask her to read more",
        "chips": {
          "costs": [
            "more of the scarcest thing she has"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She agrees to one more chapter, once, with a date attached. The date is not negotiable and neither is the once. She reads the whole thing.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "capability": {
                  "learning": 1
                },
                "flagsSet": [
                  "okonkwo-knows-your-work"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Send it, she says, and I will get to it when I get to it. It comes back six weeks later with two lines on it.",
              "effects": {}
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "She answers, sends you back to the paragraph, and the queue moves on behind you.",
        "Fifteen minutes, one clear instruction, and a reading you had not heard of."
      ],
      "mixed": [
        "You get the general version and the clock. Both are honest.",
        "The corridor is still full when you come out, and you are carrying less than you hoped."
      ]
    },
    "readRef": "/map/credential-decision",
    "evidenceLabel": "illustrative",
    "requiresFlags": [
      "start:enrolled"
    ],
    "weight": 2
  },
  {
    "id": "evt-okonkwo-cools",
    "family": "school",
    "domains": [
      "learning",
      "people"
    ],
    "label": "The margins go empty",
    "scene": "Your draft comes back with two lines on it. Good. Tighten the third section. She used to fill the margins. In the seminar she calls on you the way she calls on everyone else, which is new.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-mentor-okonkwo"
    },
    "seasonBands": [
      [
        2,
        16
      ]
    ],
    "options": [
      {
        "id": "opt-okonkwo-turn-up",
        "label": "Turn up with it done",
        "chips": {
          "costs": [
            "the reading, actually read"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The next draft has the reading in it. Her margins do not fill again, but she stays past the fifteen minutes, which is her version of the same thing.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The work is better and the feedback is the same length. She rations what she has, and this term she has rationed it elsewhere.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-ask-changed",
        "label": "Ask what changed",
        "chips": {
          "costs": [
            "hearing an answer you asked for"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She says it plainly: the drafts stopped arriving with anything in them she could work on, so the time went where it was being used. Said without heat, and then over.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The work is fine, she says, and the next student is at the door. Whether that is the whole answer is not something you find out today.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-take-it",
        "label": "Take the shorter feedback",
        "chips": {
          "costs": [
            "a term of two-line margins"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You work from the two lines. They are good lines. The section gets tighter and nothing else about the term changes.",
              "effects": {
                "capability": {
                  "learning": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "By the end of term she knows your name and not much about your work. The letter you were half counting on quietly stops being a thing she could write.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/map/credential-decision",
    "evidenceLabel": "illustrative",
    "recoveryRefs": [
      "act-small-ask-one-question"
    ],
    "requiresFlags": [
      "start:enrolled"
    ],
    "negative": true
  },
  {
    "id": "evt-okonkwo-repair",
    "family": "school",
    "domains": [
      "learning",
      "people",
      "repair"
    ],
    "label": "The rewrite, done properly",
    "scene": "You have the rewrite and this time it is done properly: her reading actually read, the third section rebuilt from the floor. Tuesday's queue is out of the door, and fifteen minutes of it might be yours.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-mentor-okonkwo"
    },
    "seasonBands": [
      [
        2,
        16
      ]
    ],
    "options": [
      {
        "id": "opt-okonkwo-hand-over",
        "label": "Hand it over, say nothing",
        "chips": {
          "costs": [
            "the wait while she reads"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "learning",
          "skill": "academic-writing",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She reads two pages standing up, puts a mark in the margin, and says come back Tuesday with the next section. The time is on the table again.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She takes it for later. Later turns out to be three weeks, and what comes back is careful and short. She is working at her own speed, not yours.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-name-gap",
        "label": "Name the gap first",
        "chips": {
          "costs": [
            "saying the unflattering part out loud"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You say what you did not do last term. She takes it in one sentence, will not discuss it further, and goes straight to the third section.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She gives you the time, and gives you less of it than she used to. Fifteen minutes becomes ten, and the ten are entirely about the work.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-ask-letter-now",
        "label": "Ask for the letter now",
        "chips": {
          "costs": [
            "spending the fifteen minutes on the ask"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Ask me at the end of term, she says, and go and finish the chapter. It is not a no and it is not anything else either.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "One good draft is not a body of work, she says, not unkindly. The fifteen minutes go on that conversation instead of on the chapter.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/map/credential-decision",
    "evidenceLabel": "illustrative",
    "requiresFlags": [
      "start:enrolled"
    ]
  },
  {
    "id": "evt-okonkwo-refuses",
    "family": "school",
    "domains": [
      "learning",
      "people",
      "credential"
    ],
    "label": "She will not write it",
    "scene": "You ask for the letter. She does not pause. I cannot write you a strong one, she says, and a lukewarm letter from me would do you more harm than no letter at all. Ask Bakare. He saw the fieldwork.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-mentor-okonkwo"
    },
    "seasonBands": [
      [
        4,
        20
      ]
    ],
    "options": [
      {
        "id": "opt-okonkwo-ask-bakare",
        "label": "Ask Bakare instead",
        "chips": {
          "costs": [
            "starting the ask again, from further back"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "systemicFlags": [
            "deadline-close"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Bakare says yes, writes it late, and writes it about the fieldwork. A narrower letter than the one you wanted, and it does the job.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "has-reference"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Bakare needs a month and the deadline is inside a month. What goes in is the application without a letter, and it goes in on time.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-ask-what-strong",
        "label": "Ask what a strong one needs",
        "chips": {
          "costs": [
            "hearing the honest list"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "She names it: sustained work she has actually seen, and one thing finished. Both take longer than this deadline. You write the list down anyway.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You get the general shape of it, and the next student is waiting. You leave with something true and nothing you can use this term.",
              "effects": {
                "capability": {
                  "regulation": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-withdraw",
        "label": "Withdraw the ask",
        "chips": {
          "costs": [
            "the application, or a season of it"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You take the ask back and thank her for saying it straight. The seminar carries on exactly as it did.",
              "effects": {
                "capability": {
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The ask goes away and the application goes with it, this round. The next round is a year off, and a year is a long time from here.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          }
        ]
      }
    ],
    "readRef": "/map/credential-decision",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "She will not write a letter she cannot write strongly, says exactly that, and names who can instead. That is a person exercising judgement honestly, and the adjacent route she points at is already on the card as a choice. A recovery route rendered after her answer would read as a way around it."
    },
    "requiresFlags": [
      "start:enrolled"
    ]
  },
  {
    "id": "evt-okonkwo-advocates",
    "family": "work",
    "domains": [
      "work",
      "learning",
      "people"
    ],
    "label": "A door you did not see",
    "scene": "She forwards an email with three lines above it. This is yours if you want it. Applications close Friday. I have already said your name to the person who reads them. It is a post you did not know existed.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-mentor-okonkwo"
    },
    "seasonBands": [
      [
        5,
        22
      ]
    ],
    "options": [
      {
        "id": "opt-okonkwo-apply",
        "label": "Apply by Friday",
        "chips": {
          "costs": [
            "the week you had planned",
            "two nights of writing"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "execution",
          "companionFlags": [
            "okonkwo-knows-your-work"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "It is yours. A post with a start date and your name on it, and the fact that she said the name first is the part you cannot repeat.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "execution": 1
                },
                "flagsSet": [
                  "employed"
                ],
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "It goes to an internal candidate. You are on a shortlist you would not have reached alone, and the person who reads them now knows the name.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It goes in by Friday and you hear nothing until the autumn, when a form letter arrives. She does not raise it and neither do you.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-talk-first",
        "label": "Ask her to talk it through",
        "chips": {
          "costs": [
            "more of her hours, on top of this"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Twenty minutes on what the post actually is, including the parts of it she would not take herself. You apply knowing what you are applying for.",
              "effects": {
                "capability": {
                  "adaptability": 1
                },
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She has no hours this week. Apply or do not, she says, I have told you what I know. Friday is where it was and you are a day down.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-let-pass",
        "label": "Let Friday go past",
        "chips": {
          "costs": [
            "a door open exactly once"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The week is already full and it stays full. Friday goes past. She does not mention it, then or later.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "Nothing is said about it. The next thing that crosses her desk goes to a student who used the last one.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-mentor-okonkwo",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-okonkwo-post-starts",
        "label": "The post starts",
        "effects": {
          "gauge": {
            "money": 1,
            "timeStructure": 1
          },
          "skills": [
            "logistics"
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "strong"
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "recoveryRefs": [
      "act-small-ask-one-question"
    ],
    "requiresFlags": [
      "start:enrolled"
    ]
  },
  {
    "id": "evt-okonkwo-leaves",
    "family": "school",
    "domains": [
      "learning",
      "people",
      "endings"
    ],
    "label": "She takes a post elsewhere",
    "scene": "The email goes to the whole list. From the autumn she is at another university, far enough that getting there is a train and a night. Her office is already half in boxes when you pass. The seminar runs again with someone else, and it will be a different seminar.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-mentor-okonkwo"
    },
    "seasonBands": [
      [
        12,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-okonkwo-last-ask",
        "label": "Ask for the last thing",
        "chips": {
          "costs": [
            "asking on the way out"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "companionFlags": [
            "okonkwo-knows-your-work"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She writes the reference before she goes, honest and specific, and it is on file. The address she leaves you is the one at the new place.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "flagsSet": [
                  "has-reference"
                ],
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She names two people in the department who could read your work now. Neither of them has read any of it yet. You have a place to start.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "flagsSet": [
                  "knows-the-route"
                ],
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-say-it",
        "label": "Say the actual thing",
        "chips": {
          "costs": [
            "a conversation with nothing to gain in it"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You tell her what the seminar did. She takes it briefly, the way she takes everything, writes an address on the back of a reading list, and goes back to the boxes.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It comes out smaller than it is. She says thank you and means it, and a corridor is not the place for the rest of it.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-okonkwo-let-term-end",
        "label": "Let the term end",
        "chips": {
          "costs": [
            "a thing left unsaid"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The term ends and the boxes go. You keep the marked-up draft with her handwriting in the margin, which turns out to be the part you use.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "capability": {
                  "learning": 1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You mean to catch her before the autumn, and the autumn arrives first. The schedule has a new name against the seminar.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-mentor-okonkwo",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/map/credential-decision",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "A person taking a post elsewhere is not a failure state. The options here are already about what the character does with an ending, and a way-on-from-here would recast her move as something done to the character rather than a choice she made about her own work."
    },
    "requiresFlags": [
      "start:enrolled"
    ],
    "negative": true
  }
];
