/**
 * Event batch "world-capacity-civic" — GENERATED by tools/build-content.mjs from events-world-capacity-civic.json.
 *
 * Authored against content/sim/AUTHORING.md by a schema-constrained author, then
 * checked by an adversarial safety verifier (two-tier boundary, capacity-event
 * boundary, never-command five, no-numbers, no-dominant-option, evidence labels,
 * voice) and repaired against its findings, then read in the rolling human review.
 * 10 records. Originally compiled from a JSON batch by tools/build-content.mjs;
 * that JSON was not retained, so THIS FILE is the authored artifact now and is
 * edited directly. Its shape stays JSON-compatible so tools/variant-hygiene.mjs
 * can keep rewriting it structurally.
 */
import type { SimEvent } from "@/content/sim/schema";

export const EVENTS_WORLD_CAPACITY_CIVIC: SimEvent[] = [
  {
    "id": "evt-back-goes-lifting",
    "family": "health",
    "domains": [
      "health",
      "capacity",
      "work"
    ],
    "label": "Your back goes",
    "scene": "You lift the box the way you have lifted a hundred boxes, and something low in your back lets go. Standing up is a strategy now. Six weeks of not lifting anything, and a physio slot that sits in the middle of a working afternoon.",
    "trigger": {
      "kind": "chance"
    },
    "seasonBands": [
      [
        1,
        16
      ]
    ],
    "options": [
      {
        "id": "opt-back-do-the-physio",
        "label": "Do the physio properly",
        "chips": {
          "costs": [
            "leaving early once a week",
            "the hours you are not paid for"
          ],
          "variance": "narrow",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:income-obligation",
              "text": "Every hour you leave early is an hour someone at home needs."
            }
          ]
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "constraintFlags": [
            "start:income-obligation"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "The exercises are boring and they work. By the end of the season you can carry your own shopping again.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "money": -1
                },
                "capability": {
                  "vitality": 2
                },
                "skills": [
                  "pacing"
                ],
                "conditionsClear": [
                  "reduced-capacity"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You get to most of the appointments. The back is better than it was and not what it was.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "money": -1
                },
                "capability": {
                  "vitality": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-back-light-duties",
        "label": "Ask for light duties",
        "chips": {
          "costs": [
            "telling them there is something wrong",
            "the shifts you get moved off"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "They move you to the counter for a stretch and nobody makes it a thing. You keep the hours and the back gets its time.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1
                },
                "capability": {
                  "vitality": 1,
                  "socialNavigation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You get the lighter work and the worse schedule with it. Fewer boxes, later nights.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "timeStructure": -1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The lighter work turns out to be fewer hours. The back gets its rest and the month gets thinner.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-back-work-through",
        "label": "Work through it",
        "chips": {
          "costs": [
            "what it takes out of every shift",
            "the sleep it costs at night"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "vitality",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It hurts for a month and then mostly stops. You keep every hour and pay for them in the evenings.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "maintenanceDebt": 1
              }
            }
          },
          {
            "name": "failure",
            "weight": 3,
            "failure": true,
            "outcome": {
              "line": "You keep every shift and the back keeps score. By the end of the season, lifting is something you plan around rather than something you do.",
              "effects": {
                "gauge": {
                  "healthEnergy": -2
                },
                "capability": {
                  "vitality": -1
                },
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "Slow, dull progress. Nothing you can point at week to week, and a season later the mornings are ordinary again."
      ]
    },
    "delayedEffects": [
      {
        "id": "de-back-does-not-settle",
        "label": "The back does not settle",
        "effects": {
          "gauge": {
            "healthEnergy": -1
          },
          "capability": {
            "vitality": -1
          },
          "conditionsSet": [
            "reduced-capacity"
          ],
          "maintenanceDebt": 1
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "failure"
        ]
      }
    ],
    "readRef": "/topics/health",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-body-ask-accommodation",
      "act-body-pace-the-week",
      "act-body-care-access"
    ],
    "requiresFlags": [
      "employed"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-sleep-will-not-come-right",
    "family": "health",
    "domains": [
      "health",
      "capacity",
      "sleep"
    ],
    "label": "A run of bad sleep",
    "scene": "Something in the schedule has broken your sleep. You are in bed at a sensible hour and awake at three, and the mornings are being paid for out of everything else. It has been weeks now, long enough that you have stopped calling it a bad week.",
    "trigger": {
      "kind": "chance"
    },
    "seasonBands": [
      [
        3,
        20
      ]
    ],
    "options": [
      {
        "id": "opt-sleep-get-it-looked-at",
        "label": "Get it looked at",
        "chips": {
          "costs": [
            "a wait for the appointment",
            "explaining it twice to two people"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "systemicFlags": [
            "waitlist",
            "coverage-gap"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Someone takes it seriously, asks the right questions, and gives you something to try. It takes most of the season to come back. It does come back.",
              "effects": {
                "gauge": {
                  "healthEnergy": 2,
                  "money": -1,
                  "timeStructure": -1
                },
                "capability": {
                  "vitality": 1,
                  "regulation": 1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You are put on a list and given a leaflet. The leaflet is not nothing. The list is months long.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "capability": {
                  "regulation": 1
                },
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-sleep-rebuild-the-week",
        "label": "Rebuild the week around it",
        "chips": {
          "costs": [
            "the evening things you drop",
            "hours moved for no visible gain"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "skill": "pacing",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You move the shifts you can move and give up the ones you cannot defend. The nights get longer and quieter.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "connection": -1
                },
                "capability": {
                  "vitality": 1
                },
                "skills": [
                  "pacing"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Half the week moves and half of it will not. It improves enough to stop being the main thing.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "timeStructure": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-sleep-ride-it-out",
        "label": "Ride it out",
        "chips": {
          "costs": [
            "the flat feeling in every afternoon"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It passes on its own, roughly when the thing that caused it passes. You lose a season of clear afternoons to it.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "maintenanceDebt": 1
              }
            }
          },
          {
            "name": "poor",
            "weight": 3,
            "failure": true,
            "outcome": {
              "line": "It does not pass. Everything takes longer, small things get dropped, and the week starts running you.",
              "effects": {
                "gauge": {
                  "healthEnergy": -2
                },
                "capability": {
                  "execution": -1,
                  "vitality": -1
                },
                "maintenanceDebt": 2
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "It takes most of the season to come back. It does come back.",
        "Nothing clever fixes it. The dull, repeated version of the same thing does."
      ],
      "mixed": [
        "Some weeks are fine now and some are not, and you can no longer predict which.",
        "It improves enough to stop being the main thing and not enough to forget about."
      ]
    },
    "readRef": "/topics/health",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-body-pace-the-week",
      "act-body-care-access"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-the-old-thing-flares",
    "family": "health",
    "domains": [
      "health",
      "capacity",
      "work"
    ],
    "label": "The old thing flares",
    "scene": "The thing you have carried since school comes back the way it does — not new, not a surprise, badly timed. You know the routine. The routine costs two weeks of the season, and a conversation at work you have had before and would rather not have again.",
    "trigger": {
      "kind": "systemic"
    },
    "seasonBands": [
      [
        1,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-flare-run-the-routine",
        "label": "Run the routine you know",
        "chips": {
          "costs": [
            "two weeks of the season",
            "the things that get postponed inside it"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "skill": "pacing",
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You know exactly what this needs and you give it exactly that. It costs the two weeks and nothing more.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "timeStructure": -1
                },
                "capability": {
                  "vitality": 1
                },
                "skills": [
                  "pacing"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The routine takes longer to work than it used to. You get there, later than you planned, with the season shorter.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-flare-tell-them-early",
        "label": "Tell them early",
        "chips": {
          "costs": [
            "saying it out loud before you have to",
            "how it is filed away about you"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You say it plainly at the start instead of explaining it at the end. The two weeks gets planned around rather than absorbed.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "disclosed-capacity"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "They are fine about it and something shifts anyway. You are on fewer of the things that need someone reliable.",
              "effects": {
                "gauge": {
                  "connection": -1,
                  "timeStructure": -1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "disclosed-capacity"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-flare-carry-it-quietly",
        "label": "Carry it quietly",
        "chips": {
          "costs": [
            "the effort of looking fine",
            "what the two weeks takes anyway"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Nobody knows and the two weeks passes. You keep every commitment you had, and spend the season's spare capacity on looking like you always do.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "regulation": 1
                },
                "maintenanceDebt": 1
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "It runs longer than two weeks and the covering stops working. Things get dropped in front of people, without the context.",
              "effects": {
                "gauge": {
                  "healthEnergy": -2,
                  "connection": -1
                },
                "capability": {
                  "regulation": -1
                },
                "maintenanceDebt": 2
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "The routine works, the way it has worked before. Two weeks small, then ordinary again."
      ]
    },
    "readRef": "/topics/health",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-body-ask-accommodation",
      "act-body-pace-the-week",
      "act-body-care-access"
    ],
    "requiresFlags": [
      "start:reduced-capacity"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-appointment-in-three-months",
    "family": "health",
    "domains": [
      "health",
      "institutions",
      "access"
    ],
    "label": "The appointment is months away",
    "scene": "The referral goes through and the first slot is three months out. Nothing about the next three months changes because of it; you simply have it now, sitting on a calendar, being far away. The person on the phone is sorry and is not the reason.",
    "trigger": {
      "kind": "systemic"
    },
    "seasonBands": [
      [
        2,
        22
      ]
    ],
    "options": [
      {
        "id": "opt-appt-take-the-slot",
        "label": "Take it and plan around",
        "chips": {
          "costs": [
            "a season of managing it yourself"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "skill": "pacing",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You put it in the calendar and build the season so it can wait. Nothing improves and nothing gets worse.",
              "effects": {
                "capability": {
                  "adaptability": 1
                },
                "skills": [
                  "pacing"
                ],
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The waiting is fine until it is not. Two weeks in the middle cost more than they should have.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-appt-cancellation-list",
        "label": "Work the cancellation list",
        "chips": {
          "costs": [
            "being reachable at no notice",
            "the calls that come to nothing"
          ],
          "variance": "wide",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:place-bound",
              "text": "A slot at short notice is only useful if you can get there."
            }
          ]
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "constraintFlags": [
            "start:place-bound",
            "start:caring-duty"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "A slot opens on a Tuesday morning and you are the one who answers. Months of waiting collapse into a phone call.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1
                },
                "capability": {
                  "execution": 1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You get called twice and cannot make either. The list keeps your name and the date stays where it was.",
              "effects": {
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "You keep the phone on you for a season and nothing comes. You have spent a lot of attention on staying available.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "waitlist"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-appt-pay-to-be-seen",
        "label": "Pay to be seen sooner",
        "chips": {
          "costs": [
            "a month's slack in one payment"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "This is the whole cushion, and there is nothing behind it."
            }
          ]
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:no-backstop",
            "start:carrying-debt"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You are seen in two weeks. It costs what a month of breathing room costs, and the waiting stops.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "healthEnergy": 1
                },
                "capability": {
                  "vitality": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You pay, you are seen, and you are referred back into the same queue you were already in.",
              "effects": {
                "gauge": {
                  "money": -2
                },
                "flagsSet": [
                  "waitlist",
                  "knows-the-route"
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/health",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-body-care-access",
      "act-body-pace-the-week"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-hands-and-the-work",
    "family": "health",
    "domains": [
      "health",
      "capacity",
      "work"
    ],
    "label": "Your hands start complaining",
    "scene": "Weeks into the new pattern your hands begin telling you about it. Pins and needles by the end of a shift, a grip that goes vague when you are tired. Nothing dramatic, nothing that stops you — a thing that is now part of every hour you work.",
    "trigger": {
      "kind": "chance"
    },
    "seasonBands": [
      [
        4,
        20
      ]
    ],
    "options": [
      {
        "id": "opt-hands-change-the-setup",
        "label": "Change the setup",
        "chips": {
          "costs": [
            "what the kit costs",
            "looking fussy in front of people"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "adaptability",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "The change is small and slightly humiliating and it works within a month.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": 1
                },
                "capability": {
                  "vitality": 1
                },
                "skills": [
                  "pacing"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It helps on the days you remember to do it that way, which is most of them.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "vitality": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-hands-cut-the-hours",
        "label": "Cut the hours back",
        "chips": {
          "costs": [
            "the money those hours were",
            "the schedule you asked to be on"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "gauge": "money",
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Fewer hours and the hands settle. The month is tighter in the way fewer hours make a month tighter.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": 2
                },
                "capability": {
                  "vitality": 2
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You give up the hours and get put back on them within a month, because the schedule needs someone.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-hands-keep-going",
        "label": "Keep going as you are",
        "chips": {
          "costs": [
            "the last hour of every shift"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "vitality",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You keep every hour. The hands stay about the same and you stop noticing, mostly.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "maintenanceDebt": 1
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "It gets worse quietly until a shift ends early. Now it is a thing you have to deal with rather than a thing you can plan.",
              "effects": {
                "gauge": {
                  "healthEnergy": -2,
                  "money": -1
                },
                "capability": {
                  "vitality": -2
                },
                "conditionsSet": [
                  "reduced-capacity"
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "You change how you hold things. The end of the shift stops being the worst part of it."
      ]
    },
    "readRef": "/topics/work",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-body-ask-accommodation",
      "act-body-care-access",
      "act-body-pace-the-week"
    ],
    "requiresFlags": [
      "employed"
    ],
    "negative": true,
    "weight": 1
  },
  {
    "id": "evt-benefit-refused-on-a-technicality",
    "family": "civic",
    "domains": [
      "institutions",
      "money",
      "paperwork"
    ],
    "label": "Refused on a technicality",
    "scene": "The letter says the application is refused. Not on the merits — on a box left blank, on a page you were never sent. The money you had built the month around is not coming, and the appeal has its own deadline, printed small at the bottom.",
    "trigger": {
      "kind": "systemic"
    },
    "seasonBands": [
      [
        1,
        18
      ]
    ],
    "options": [
      {
        "id": "opt-benefit-appeal-it",
        "label": "Appeal it",
        "chips": {
          "costs": [
            "evenings of paperwork",
            "hold music, twice a week"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "skill": "logistics",
          "systemicFlags": [
            "benefits-denied"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You send the page they never sent you, with the date on it, and the decision is reversed. The money arrives backdated, in one payment.",
              "effects": {
                "gauge": {
                  "money": 2
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "It goes through eventually. Eventually is two months after the month you needed it for.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": -1
                },
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The appeal is refused on the same ground, restated. You have spent a season of evenings and learned the exact shape of the wall.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "benefits-denied",
                  "coverage-gap"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-benefit-start-again-clean",
        "label": "Start again, clean",
        "chips": {
          "costs": [
            "the wait, from the beginning",
            "the season you go without it"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "The second application is perfect and slow. It is approved from the date you sent it, not the date you first needed it.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": -1
                },
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It sits in a queue for the whole season. Each time you ask, you are told there is nothing wrong with it.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-benefit-cover-the-hole",
        "label": "Cover the hole yourself",
        "chips": {
          "costs": [
            "the extra shifts you pick up",
            "the evenings they come out of"
          ],
          "variance": "moderate",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "There is nobody to carry the month for you while a decision gets made."
            }
          ]
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "gauge": "money",
          "capability": "vitality",
          "constraintFlags": [
            "start:no-backstop"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You work the hole shut. The month closes level, on your hours, and the season goes to doing that.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": -1,
                  "timeStructure": -1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Most of it gets covered. The rest goes on the card, where it waits for you.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "carrying-balance"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "mixed": [
        "The decision is reversed and the backdating is not. You get it from now."
      ]
    },
    "readRef": "/topics/money",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-work-first-job-hunt",
      "act-money-cheap-or-lasting",
      "act-body-care-access"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-on-the-waiting-list",
    "family": "civic",
    "domains": [
      "institutions",
      "housing",
      "access"
    ],
    "label": "You get on the list",
    "scene": "You get on the list. It is long enough that the woman taking your details will not guess at a date, and honest enough to say so. Your name is on it; your situation is not. Anything that changes has to be reported, or you start again at the bottom.",
    "trigger": {
      "kind": "systemic"
    },
    "seasonBands": [
      [
        10,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-waitlist-hold-and-report",
        "label": "Stay on it, report everything",
        "chips": {
          "costs": [
            "a form every time anything moves",
            "planning around a date nobody has"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "skill": "logistics",
          "systemicFlags": [
            "waitlist"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "Your name comes up sooner than anyone suggested it would. The thing you were told to expect in years arrives in seasons.",
              "effects": {
                "gauge": {
                  "money": 2,
                  "timeStructure": 1
                },
                "conditionsClear": [
                  "unstable-housing"
                ],
                "flagsClear": [
                  "waitlist"
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You stay on it, correctly, all season. Nothing arrives. Your place in the queue is exactly where you left it.",
              "effects": {
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "A change goes unreported for two weeks and the file is closed. The letter explaining this arrives after the deadline to contest it.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "flagsClear": [
                  "waitlist"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-waitlist-take-what-is-there",
        "label": "Take what is available now",
        "chips": {
          "costs": [
            "the commute it comes with",
            "giving up your place on the list"
          ],
          "variance": "moderate",
          "reversibility": "locks in"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "adaptability",
          "constraintFlags": [
            "start:place-bound"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You take the apartment that is available rather than the one you wanted. It is settled by the end of the month, and it is far out.",
              "effects": {
                "gauge": {
                  "timeStructure": -1,
                  "money": 1
                },
                "conditionsSet": [
                  "commute-heavy"
                ],
                "conditionsClear": [
                  "unstable-housing"
                ],
                "flagsClear": [
                  "waitlist"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It is yours and it is not good. Sorted, in the sense that you no longer have to think about it every week.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "conditionsClear": [
                  "unstable-housing"
                ],
                "flagsClear": [
                  "waitlist"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-waitlist-look-outside",
        "label": "Look outside the system",
        "chips": {
          "costs": [
            "the deposit",
            "paying the difference every month"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:family-backstop",
            "start:carrying-debt"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You find something on the open market and pay for the speed. The list stops mattering and the rent starts.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "timeStructure": 1
                },
                "conditionsClear": [
                  "unstable-housing"
                ],
                "flagsClear": [
                  "waitlist"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You look all season, get outbid on two, and stay where you are with the deposit still sitting there.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/money",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-housing-lease-renewal",
      "act-housing-move-back"
    ],
    "excludesFlags": [
      "start:stable-housing"
    ],
    "weight": 2
  },
  {
    "id": "evt-jury-summons-arrives",
    "family": "civic",
    "domains": [
      "institutions",
      "obligation",
      "work"
    ],
    "label": "A jury summons arrives",
    "scene": "The summons is in the post, correctly addressed, with a date in the middle of everything. The time off is not optional. Whether any of it is paid depends on where you work and which state you are in. The reply card wants an answer this week, and lists the grounds for getting out.",
    "trigger": {
      "kind": "chance"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-jury-serve",
        "label": "Serve",
        "chips": {
          "costs": [
            "two weeks of your hours",
            "the pay the days do not cover"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "constraintFlags": [
            "start:income-obligation",
            "start:caring-duty"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Two weeks of a room full of strangers doing something serious, carefully. You come back two weeks's pay short, having watched twelve people decide something.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "capability": {
                  "socialNavigation": 1,
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You sit in the waiting room for days and are released without being seated. The two weeks is gone either way.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-jury-ask-to-defer",
        "label": "Ask to defer",
        "chips": {
          "costs": [
            "it comes back on a date you do not pick"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "strong",
            "weight": 3,
            "outcome": {
              "line": "The deferral is granted without argument. It is moved, not cancelled, and the new date is theirs to set.",
              "effects": {
                "flagsSet": [
                  "jury-deferred"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The deferral is refused and the date stands. You have spent the week that was for arranging cover on asking instead.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-jury-claim-hardship",
        "label": "Claim the hardship exemption",
        "chips": {
          "costs": [
            "putting your situation in writing",
            "having it assessed by someone"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "constraintFlags": [
            "start:caring-duty",
            "start:income-obligation",
            "start:reduced-capacity"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You write down what two weeks without pay would actually do and someone reads it and agrees. You are excused.",
              "effects": {
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The grounds do not fit your situation as they have written the grounds. You serve anyway, having explained yourself for nothing.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1,
                  "healthEnergy": -1
                }
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-jury-comes-back",
        "label": "The deferred summons comes back",
        "effects": {
          "gauge": {
            "timeStructure": -1
          }
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "strong"
        ]
      }
    ],
    "readRef": "/guidance",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-people-share-the-caring-duty",
      "act-body-pace-the-week"
    ],
    "negative": true,
    "weight": 1
  },
  {
    "id": "evt-records-error-eats-a-month",
    "family": "civic",
    "domains": [
      "institutions",
      "paperwork",
      "school"
    ],
    "label": "An office has you down wrong",
    "scene": "An office has you down as withdrawn. You are not withdrawn. Somewhere between two systems a box moved, and until it moves back you are not enrolled, not on the list for anything, and not answerable to a human being who can simply fix it.",
    "trigger": {
      "kind": "systemic"
    },
    "seasonBands": [
      [
        1,
        12
      ]
    ],
    "options": [
      {
        "id": "opt-records-go-in-person",
        "label": "Go in person and wait",
        "chips": {
          "costs": [
            "a day you cannot take off",
            "the trip across town"
          ],
          "variance": "moderate",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:place-bound",
              "text": "The office is not near anything you can reach on a weekday."
            }
          ]
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "constraintFlags": [
            "start:place-bound",
            "start:income-obligation"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "One person with the right access undoes it in a minute, having taken a month to reach.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "execution": 1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You are sent to a different counter and then to a phone line. It is logged, at least, and logged is not fixed.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "records-error"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-records-build-the-paper-trail",
        "label": "Build the paper trail",
        "chips": {
          "costs": [
            "a slower route",
            "writing the same thing to three addresses"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "skill": "logistics",
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Everything in writing, dated, copied. It takes the whole season and when it lands it stays landed.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The file is correct and the systems have not spoken to each other yet. You are enrolled in one place and not in the other.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "flagsSet": [
                  "records-error"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-records-absorb-the-month",
        "label": "Absorb the month",
        "chips": {
          "costs": [
            "the month itself",
            "everything that assumed you were on the list"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "regulation",
          "systemicFlags": [
            "records-error"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It corrects itself the following month with no explanation. You spent no evenings on it and the month is gone anyway.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "failure",
            "weight": 3,
            "failure": true,
            "outcome": {
              "line": "It does not correct itself. By the time anyone looks at it, the deadline that mattered has gone past and cannot be reopened.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "records-error"
                ],
                "maintenanceDebt": 2
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "It is corrected, and the record of it having been wrong stays on the file underneath."
      ]
    },
    "delayedEffects": [
      {
        "id": "de-records-error-echoes",
        "label": "The error turns up again downstream",
        "effects": {
          "gauge": {
            "timeStructure": -1
          },
          "flagsSet": [
            "records-error"
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "failure"
        ]
      }
    ],
    "readRef": "/guidance",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-learn-study-alongside-work",
      "act-learn-exit-program"
    ],
    "requiresFlags": [
      "start:enrolled"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-the-rule-you-planned-around-changes",
    "family": "civic",
    "domains": [
      "institutions",
      "money",
      "planning"
    ],
    "label": "The rule changes under you",
    "scene": "The rule changes at the turn of the year. The threshold you were sitting just under is somewhere else now, and the plan you built on it — the hours, the timing, the thing you were waiting to become eligible for — was built on a line that has moved.",
    "trigger": {
      "kind": "systemic"
    },
    "seasonBands": [
      [
        13,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-rule-rebuild-the-plan",
        "label": "Rebuild the plan",
        "chips": {
          "costs": [
            "a season of re-doing settled arithmetic",
            "the timeline you had told people"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "adaptability",
          "systemicFlags": [
            "rule-changed"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You rebuild it around the new line. It is a worse plan than the old one and it is a plan.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "capability": {
                  "adaptability": 2
                },
                "flagsSet": [
                  "rule-changed"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The new arithmetic does not close. You get most of a plan and a gap you will have to cover from somewhere.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "rule-changed",
                  "coverage-gap"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-rule-find-the-other-door",
        "label": "Find the other door",
        "chips": {
          "costs": [
            "reading the whole notice",
            "asking people who have already done it"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "gauge": "connection",
          "skill": "logistics",
          "systemicFlags": [
            "rule-changed"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "There is a second route, badly signposted, that the change did not touch. Someone who has walked it tells you where it starts.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "connection": 1
                },
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "There is another route. It is longer and it costs more, and you leave with the name of the form and the address it goes to.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "flagsSet": [
                  "knows-the-route",
                  "rule-changed"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-rule-hold-to-the-old-terms",
        "label": "Hold to the old terms",
        "chips": {
          "costs": [
            "betting a season on being grandfathered in"
          ],
          "variance": "very wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "systemicFlags": [
            "rule-changed"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "The transitional provision covers people already in the system. You were already in the system. Nothing changes for you, and nothing has to be rebuilt.",
              "effects": {
                "gauge": {
                  "money": 2,
                  "timeStructure": 1
                },
                "capability": {
                  "adaptability": 1
                }
              }
            }
          },
          {
            "name": "failure",
            "weight": 3,
            "failure": true,
            "outcome": {
              "line": "There is no transitional provision, or there is one and it does not reach you. A season spent waiting for a rule that already went.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "rule-changed"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "A season of re-doing arithmetic you had already done. The shape survives; the timeline does not."
      ]
    },
    "delayedEffects": [
      {
        "id": "de-rule-change-lands-late",
        "label": "The old terms run out",
        "effects": {
          "gauge": {
            "money": -1
          },
          "flagsSet": [
            "rule-changed"
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "failure"
        ]
      }
    ],
    "readRef": "/topics/money",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-money-file-your-taxes",
      "act-work-sideways-move"
    ],
    "negative": true,
    "weight": 2
  }
];
