/**
 * Event batch "comp-friends" — GENERATED by tools/build-content.mjs from events-comp-friends.json.
 *
 * Authored against content/sim/AUTHORING.md by a schema-constrained author, then
 * checked by an adversarial safety verifier (two-tier boundary, capacity-event
 * boundary, never-command five, no-numbers, no-dominant-option, evidence labels,
 * voice) and repaired against its findings, then read in the rolling human review.
 * 12 records. Originally compiled from a JSON batch by tools/build-content.mjs;
 * that JSON was not retained, so THIS FILE is the authored artifact now and is
 * edited directly. Its shape stays JSON-compatible so tools/variant-hygiene.mjs
 * can keep rewriting it structurally.
 */
import type { SimEvent } from "@/content/sim/schema";

export const EVENTS_COMP_FRIENDS: SimEvent[] = [
  {
    "id": "evt-mo-invite",
    "family": "people",
    "domains": [
      "relationships",
      "friendship"
    ],
    "label": "Mo's Saturday thing",
    "scene": "Mo texts about Saturday — someone is back in town, the usual place, no plan beyond that. The message has the tone Mo uses when it does not matter whether you come, which is the tone Mo uses when it does.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-friend-mo"
    },
    "seasonBands": [
      [
        1,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-mo-go-properly",
        "label": "Go, and stay late",
        "chips": {
          "costs": [
            "a Saturday",
            "the energy Sunday was counting on"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "gauge": "connection",
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "It is the good version of the night — nobody performing, the old jokes still working. You get home late and it was worth the Sunday.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "A decent evening. Mo is on good form and asks you real questions, which is the whole reason you go.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 1,
            "outcome": {
              "line": "You are tired and it shows, and the evening is fine anyway. Mo walks you to the bus and says the thing about doing this more often.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "healthEnergy": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-short-version",
        "label": "Go for an hour",
        "chips": {
          "costs": [
            "an evening cut in half"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You show up, you are properly there, you go. Mo notices you came and does not comment on you leaving.",
              "effects": {
                "gauge": {
                  "connection": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You arrive as it is warming up and leave before it does. Nothing is lost. Nothing much is gained either.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-mo-honest-no",
        "label": "Say no, and say why",
        "chips": {
          "costs": [
            "telling Mo the unflattering version"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You tell Mo what the season actually looks like from inside it. Mo says fair enough, and sends a photo from the pub later, which is its own kind of answer.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Mo reads it and sends back something short. The evening happens without you and you hear about it the way everyone else does.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "Nothing memorable happens and you are glad you went. Somebody forgets whose round it is and nobody minds enough to work it out."
      ]
    },
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 3
  },
  {
    "id": "evt-mo-drift",
    "family": "people",
    "domains": [
      "relationships",
      "friendship"
    ],
    "label": "The thread goes quiet",
    "scene": "Mo's birthday happens and you find out from the group thread afterwards. Scrolling back, the last messages Mo sent you were questions you never got round to answering. Nothing has been said about it. Nothing needs to be.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-friend-mo"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-mo-answer-late",
        "label": "Answer the old messages",
        "chips": {
          "costs": [
            "an evening",
            "answering months late"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Mo answers the next day, three lines, warm enough. Nothing is said about the gap. The thread is a thread again, thinner than it was.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Mo answers a week later, briefly and politely. You have made the attempt; what Mo does with it from here is Mo's.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "outcome": {
              "line": "No answer. The messages sit there, read. You have said your part, and your part is the whole of what you control.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-real-version",
        "label": "Send the true version",
        "chips": {
          "costs": [
            "saying the unflattering part out loud"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "regulation",
          "gauge": "connection",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "You write the actual reason you went quiet. Mo writes back at the same length, which Mo does not do for nothing.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Mo reads it, says that makes sense, and asks about something else. The gap is acknowledged and not discussed.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It sits unanswered for a long while. Whether Mo comes back to it runs on Mo's clock, and you do not get to set that clock.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-let-it",
        "label": "Leave the thread alone",
        "chips": {
          "costs": [
            "a season of not being the one who texts"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "strength": 0.3
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The thread stays where it is. You think about it on and off and do nothing about it, which is also a decision.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "neglect": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 1,
            "outcome": {
              "line": "Nothing happens and nothing gets worse this season. Some things keep for longer than you expect them to.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "neglect": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-mo-repair",
    "family": "people",
    "domains": [
      "relationships",
      "friendship",
      "repair"
    ],
    "label": "After you went first",
    "scene": "You said the true thing — that you dropped it, that you know you dropped it, and that you would like it back. Mo has read the message. The reply is not instant. What happens next is not the part you get to decide.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-friend-mo"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-mo-leave-ball",
        "label": "Leave it with Mo",
        "chips": {
          "costs": [
            "not knowing, for a while"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Mo replies at the end of the week and suggests a date that is far off and real. It goes in the calendar.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "A short reply, civil, nothing scheduled. It landed somewhere. Not where you wanted it to land, and not nowhere.",
              "effects": {}
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "outcome": {
              "line": "Nothing comes back this season. The attempt stands exactly where you left it, which is where attempts stand.",
              "effects": {
                "capability": {
                  "regulation": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-follow-once",
        "label": "Follow up once, then stop",
        "chips": {
          "costs": [
            "the discipline of only once"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You send one more, short, with no pressure in it. Mo answers that one, and the answer is an ordinary answer about an ordinary Thursday.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Mo answers the second message with something brief and does not pick the thread up. You said once, and once is where you stop.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "outcome": {
              "line": "Nothing comes back. You told yourself you would stop after one, and you stop, which costs more than sending the next one would have.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-show-up",
        "label": "Turn up for the small thing",
        "chips": {
          "costs": [
            "a weekday evening",
            "the risk of being unwanted there"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "gauge": "timeStructure",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "You remember the date of the thing Mo mentioned once, and you are outside at the end of it. Mo does not say much. Mo does not have to.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You show up for it. It is slightly awkward at the start and entirely fine by the end.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You turn up and Mo is not there. You wait outside a while in the cold, message to say you came, and get nothing back this season.",
              "effects": {
                "gauge": {
                  "timeStructure": -1,
                  "healthEnergy": -1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-mo-refuses",
    "family": "people",
    "domains": [
      "relationships",
      "friendship",
      "boundaries"
    ],
    "label": "Mo asks for space",
    "scene": "You ask whether Mo wants to come to the thing. Mo says no — not annoyed, not cold. Says the timing does not work, and would rather not do the version where you both pretend everything is fine. Will be in touch, and does not say when.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-friend-mo"
    },
    "seasonBands": [
      [
        3,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-mo-take-it",
        "label": "Take it at face value",
        "chips": {
          "costs": [
            "the urge to fix it tonight"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You say all right, and mean it. The conversation ends without either of you making it into something worse than it is.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "flagsSet": [
                  "mo-asked-for-space"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You say all right and then spend the week composing messages you do not send. The no holds. So does the week.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "mo-asked-for-space"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-one-line",
        "label": "Say you will be around",
        "chips": {
          "costs": [
            "saying it once and never again"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "One line: here when you want it, no clock on it. Mo reads it and does not reply, and that is not the same thing as nothing.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "flagsSet": [
                  "mo-asked-for-space"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It reads as pressure however you word it. Mo answers with a thumbs-up, which closes the subject neatly.",
              "effects": {
                "flagsSet": [
                  "mo-asked-for-space"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-push",
        "label": "Ask for the reason",
        "chips": {
          "costs": [
            "asking a second time"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Mo tells you. It is about Mo's year more than about yours, and knowing it does not move the answer an inch.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "mo-asked-for-space"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "Mo says it again, shorter, and the space Mo asked for gets wider. The answer was already the answer before you asked.",
              "effects": {
                "flagsSet": [
                  "mo-asked-for-space"
                ],
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "neglect": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Mo asked for space. That is Mo's decision, not a setback with a route out of it, and putting a way back on this card would treat a friend's no as a problem to be solved. No band here is marked as a failure for the same reason: what asking twice costs is Mo's answer, given again."
    },
    "weight": 2
  },
  {
    "id": "evt-mo-deepen",
    "family": "people",
    "domains": [
      "relationships",
      "friendship"
    ],
    "label": "A Wednesday, and a van",
    "scene": "Mo asks you to come on a Wednesday and will not say why over text, which Mo has never done. The address turns out to be Mo's apartment, half in boxes. Mo is moving out of something and has told almost nobody. There is a van booked and no one else coming.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-friend-mo"
    },
    "seasonBands": [
      [
        8,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-mo-take-the-day",
        "label": "Take the whole day",
        "chips": {
          "costs": [
            "a weekday you cannot spare",
            "your back, tomorrow"
          ],
          "variance": "moderate",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:income-obligation",
              "text": "A weekday off is money you have already promised to somebody else."
            },
            {
              "when": "start:place-bound",
              "text": "Getting to the other town and back eats most of the day by itself."
            }
          ]
        },
        "sensitivity": {
          "gauge": "timeStructure",
          "capability": "vitality",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You carry boxes and say nothing useful all day, which turns out to be the correct amount. By evening Mo is telling you the whole of it.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "The van gets loaded. Mo talks in the cab on the way over, sideways, in the manner Mo talks about things.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 1,
            "outcome": {
              "line": "It takes far longer than the day had in it and you are wrecked by the end of it. Mo noticed that you stayed.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-half-day",
        "label": "Give the hours you have",
        "chips": {
          "costs": [
            "an afternoon",
            "leaving before the talking starts"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You do the heavy end and go. Mo texts that night, at length, which was always the part that mattered.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You are there for the boxes and gone before anything gets said. Mo does not mention it either way.",
              "effects": {
                "gauge": {
                  "connection": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-call-instead",
        "label": "Phone, and be honest",
        "chips": {
          "costs": [
            "saying you cannot come"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You tell Mo plainly that you cannot get there, and then you stay on the phone for two hours while the boxes get taped up in the background.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You call. It is not the same as being in the room and you both know it. Mo says thanks for ringing and means it.",
              "effects": {
                "gauge": {
                  "connection": 1
                }
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "excludesFlags": [
      "mo-asked-for-space"
    ],
    "weight": 2
  },
  {
    "id": "evt-mo-leaves",
    "family": "people",
    "domains": [
      "relationships",
      "friendship",
      "endings"
    ],
    "label": "The thread just ends",
    "scene": "You send Mo something the two of you would have laughed at in school. It sits unread for a week, then read, then nothing. There is no argument here to have and no announcement to answer. The thread has simply stopped being a thread.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-friend-mo"
    },
    "seasonBands": [
      [
        5,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-mo-last-message",
        "label": "Send one honest message",
        "chips": {
          "costs": [
            "writing it knowing it may not be answered"
          ],
          "variance": "moderate",
          "reversibility": "locks in"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You write what Mo was to the eighteen-year-old you were. Mo replies, warmly and briefly, and neither of you writes again after that.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "No reply. The message is honest and it is also just sitting there. You stop checking, eventually, and then stop noticing that you stopped.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-no-message",
        "label": "Let it end quietly",
        "chips": {
          "costs": [
            "not saying the thing"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "sensitivity": {
          "strength": 0.3
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "It ends the way threads end, without a last line in it. You keep the photographs and you lose the person.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 1,
            "outcome": {
              "line": "No ceremony. The thread stays in your phone where it stopped, and you find you can read back through it without wanting to add anything to the end.",
              "effects": {
                "capability": {
                  "adaptability": 1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-door-open",
        "label": "Leave your side open",
        "chips": {
          "costs": [
            "carrying it unresolved"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/topics/relationships",
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You do not chase it and you do not close it. Years from now you will still know which city Mo is in, and that will be all of it.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You send the birthday message each year and stop expecting anything back. It is a small steady thing that you do, and it is yours.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "negative": true,
    "weight": 1
  },
  {
    "id": "evt-lu-doorstep",
    "family": "home",
    "domains": [
      "relationships",
      "neighbors",
      "place"
    ],
    "label": "Lu on the step",
    "scene": "Lu is on the step with a parcel of yours that has been sitting in Lu's hallway since Tuesday. The handing-over takes no time at all, and then does not end. Lu mentions the bins, the man at the corner shop, the noise upstairs. It is not urgent. It is not nothing.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-neighbor-lu"
    },
    "seasonBands": [
      [
        1,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-lu-stay-on-step",
        "label": "Stay on the step",
        "chips": {
          "costs": [
            "a chunk of the evening"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "gauge": "timeStructure",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You stand there until it gets cold, hearing about the street. You go in knowing things about where you live that you did not know.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It goes on longer than the evening had spare. You are pleasant about it and a little late for everything after it.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "timeStructure": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-do-the-thing",
        "label": "Do the bins on your way",
        "chips": {
          "costs": [
            "five minutes and a smell"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You wheel both bins out without making an announcement of it. Nothing is said. The step conversation is longer next time.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You do it. Lu was out. It is not clear that anybody noticed, which is not really the point of doing it.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-lu-brief",
        "label": "Take the parcel and go",
        "chips": {
          "costs": [
            "being the neighbor who is always rushing"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You are polite and quick and back inside with the evening intact. There will be another step conversation.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You are halfway up the stairs before Lu has finished the sentence. The door closes behind both of you.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "The conversation goes nowhere pleasantly and takes a while doing it. Lu is in no hurry and, for once, neither are you."
      ]
    },
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 3
  },
  {
    "id": "evt-lu-quiet",
    "family": "people",
    "domains": [
      "relationships",
      "neighbors",
      "place"
    ],
    "label": "The door stops opening",
    "scene": "The hall light is on and the door does not open when you pass, which it used to. Your parcels have started going back to the depot. It has been a long while since you knocked, and Lu has weeks that Lu does not explain. From the sidewalk the two look identical.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-neighbor-lu"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-lu-knock",
        "label": "Knock with no reason",
        "chips": {
          "costs": [
            "turning up without a pretext"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Lu answers, looks briefly surprised, and talks about the gutters for as long as you can stand. The door opens the next time as well.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "No answer. You can hear the television through the door and you leave it at that. Some weeks are Lu's own and are not explained.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-note",
        "label": "Put a note through",
        "chips": {
          "costs": [
            "writing it without making it a request"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The note says nothing important on purpose. A week later there is a jar of something on your step with no label on it.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "No reply comes. The note was not a demand and you do not put a second one through.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-leave-be",
        "label": "Let the street be quiet",
        "chips": {
          "costs": [
            "a season of not knocking"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "strength": 0.3
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You pass the door and do not knock, several times over, until passing the door is simply the normal thing to do.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "neglect": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 1,
            "outcome": {
              "line": "You leave Lu to it. The hall light goes on and off on its own schedule, and you stop reading anything into it either way.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "neglect": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-lu-repair",
    "family": "people",
    "domains": [
      "relationships",
      "neighbors",
      "repair"
    ],
    "label": "The gutter and the gate",
    "scene": "You cleared the gutter over both doors while the ladder was already out, and said nothing about having done it. The next morning the gate that always sticks has been oiled. Neither thing has been mentioned by anybody. This appears to be how it is done here.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-neighbor-lu"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-lu-wordless",
        "label": "Keep it wordless",
        "chips": {
          "costs": [
            "never getting thanked for it"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You carry on doing small things and saying nothing about them. The exchange settles into a rhythm neither of you names.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You keep at it and nothing comes back this season. It is not obvious that it is landing, and it may well be landing anyway.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-knock-ask",
        "label": "Knock and ask about the week",
        "chips": {
          "costs": [
            "an hour",
            "a bad cup of tea"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "gauge": "connection",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Lu makes tea you do not enjoy and tells you about the man who used to run the shop. You stay for the whole of it.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Lu is not in, or is not answering the door. The shop story keeps until some other week, as those stories do.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-offer-ladder",
        "label": "Offer the ladder next time",
        "chips": {
          "costs": [
            "storing it in your hallway"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The ladder gets used, returned cleaner than it went out, and never mentioned. This is apparently the arrangement now.",
              "effects": {
                "flagsSet": [
                  "street-arrangement"
                ],
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The offer sits unused for a long while. Then one morning the ladder is gone and back again before you had noticed either.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-lu-refuses",
    "family": "people",
    "domains": [
      "relationships",
      "neighbors",
      "boundaries"
    ],
    "label": "The emergency contact line",
    "scene": "The form wants a local name and number for emergencies, and you have exactly one neighbor. Lu reads the line, hands the form back, and says no — not unkindly, and without saying why. Then asks whether you have eaten.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-neighbor-lu"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-lu-take-no",
        "label": "Take the no, stay for tea",
        "chips": {
          "costs": [
            "a form still unfinished"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You say fine, and answer the question about dinner instead. The no stays a no and the evening is not affected by it.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "regulation": 1
                },
                "flagsSet": [
                  "lu-declined-contact"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You are more disappointed than the situation warrants and a bit of it shows. Lu changes the subject, twice, kindly.",
              "effects": {
                "flagsSet": [
                  "lu-declined-contact"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-ask-once",
        "label": "Ask once if it's forms",
        "chips": {
          "costs": [
            "asking a second time"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Lu says it is not about you and does not elaborate on what it is about. The answer is the same answer.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "lu-declined-contact"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "outcome": {
              "line": "It comes out sounding like negotiation. Lu goes formal about it, and stays formal on the step for a good while afterwards.",
              "effects": {
                "flagsSet": [
                  "lu-declined-contact"
                ],
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-blank-line",
        "label": "Leave the line blank",
        "chips": {
          "costs": [
            "handing in a form with a hole in it"
          ],
          "variance": "moderate",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "There is nobody else's name to put in the box, and the box knows it."
            }
          ]
        },
        "sensitivity": {
          "systemicFlags": [
            "waitlist"
          ],
          "strength": 0.4
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You hand it in incomplete. Nobody says anything about it for months, and then the letter arrives.",
              "effects": {
                "flagsSet": [
                  "no-local-contact",
                  "lu-declined-contact"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "The form comes back for the missing field, and the whole thing starts again at the back of the queue.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "flagsSet": [
                  "no-local-contact",
                  "lu-declined-contact"
                ]
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-lu-contact-gap",
        "label": "The form with the hole in it",
        "effects": {
          "gauge": {
            "timeStructure": -1
          },
          "flagsSet": [
            "no-local-contact"
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "poor"
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Lu declined to be named, and another person's no is not a setback to be recovered from — a way back offered on this card would read as a route around Lu's decision. No band here is marked as a failure for the same reason: what the form still needs is the errand it always was, and not a recovery from anything Lu did."
    },
    "weight": 2
  },
  {
    "id": "evt-lu-arrangement",
    "family": "home",
    "domains": [
      "relationships",
      "neighbors",
      "place"
    ],
    "label": "The spare key offer",
    "scene": "It has settled into a shape neither of you has named. Your parcels live in Lu's hallway. Lu's shopping comes up your stairs when the lift is out. Neither of you thanks the other. Lu says, apropos of nothing, that the spare key could live with you if you wanted it to.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-neighbor-lu"
    },
    "seasonBands": [
      [
        4,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-lu-key-both-ways",
        "label": "Take the key, give yours",
        "chips": {
          "costs": [
            "somebody else having your key"
          ],
          "variance": "narrow",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "gauge": "connection",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "Both keys change hands on the step with no ceremony attached. The building gets easier in ways you keep noticing for months afterwards.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "timeStructure": 1
                },
                "flagsSet": [
                  "street-arrangement"
                ],
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You swap keys. Nothing dramatic follows. Parcels, plants, the boiler man — the small friction of a week quietly drops.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "flagsSet": [
                  "street-arrangement"
                ],
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 1,
            "outcome": {
              "line": "It is fine, and it is also a standing obligation you did not have last week. The boiler man, the plants, a Saturday morning that is now spoken for.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "flagsSet": [
                  "street-arrangement"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-key-one-way",
        "label": "Take Lu's, keep yours",
        "chips": {
          "costs": [
            "an imbalance you can feel"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You take the key. It is useful. You are aware, now and then, of the shape of the thing you did not offer back.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The key lives in your drawer and the traffic runs one way down the hall. Lu does not raise it, and does not offer anything further.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-decline-key",
        "label": "Say it's enough as is",
        "chips": {
          "costs": [
            "turning down something offered"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You say the parcels are plenty. Lu says right you are, and the step conversations carry on exactly as they were.",
              "effects": {
                "gauge": {
                  "connection": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It comes out as a refusal rather than a boundary. Lu takes it perfectly well and does not offer a second time.",
              "effects": {}
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-lu-moves",
    "family": "people",
    "domains": [
      "relationships",
      "neighbors",
      "place",
      "endings"
    ],
    "label": "A letting board goes up",
    "scene": "There is a letting board on the railing outside Lu's window. Lu tells you on the step, in the same voice as the bins: a place nearer family, going at the end of the month. The arrangement ends with the tenancy. Lu is not asking you to feel anything about it.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-neighbor-lu"
    },
    "seasonBands": [
      [
        14,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-lu-help-move",
        "label": "Help with the move",
        "chips": {
          "costs": [
            "a weekend",
            "a van you have to drive"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "vitality",
          "gauge": "timeStructure",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You load the van and drink tea out of the last unpacked mug. Lu shakes your hand at the end of it, which Lu has never done before.",
              "effects": {
                "flagsClear": [
                  "street-arrangement"
                ],
                "relationships": [
                  {
                    "id": "arc-neighbor-lu",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It rains and takes the whole day and neither of you says the thing. The van goes. The hallway is just a hallway again.",
              "effects": {
                "gauge": {
                  "connection": -1,
                  "healthEnergy": -1
                },
                "flagsClear": [
                  "street-arrangement"
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-swap-numbers",
        "label": "Swap numbers and mean it",
        "chips": {
          "costs": [
            "a promise you may not keep"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You text about the street sometimes, and about the man at the shop. It is thinner than the step was, and it is something.",
              "effects": {
                "flagsClear": [
                  "street-arrangement"
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The number goes in your phone. A few messages, then longer gaps, then none. It is still in there, under a surname you had to ask for.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "flagsClear": [
                  "street-arrangement"
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lu-end-at-door",
        "label": "Let it end at the door",
        "chips": {
          "costs": [
            "no last conversation"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.3
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You say goodbye the way neighbors do, at the door, briefly. Lu prefers it that way, and you know that by now.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "flagsClear": [
                  "street-arrangement"
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The board comes down, the new tenants arrive with their own boxes, and you never did knock that last time.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "flagsClear": [
                  "street-arrangement"
                ],
                "companions": [
                  {
                    "arcId": "arc-neighbor-lu",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "negative": true,
    "weight": 1
  }
];
