/**
 * Event batch "comp-family" — GENERATED by tools/build-content.mjs from events-comp-family.json.
 *
 * Authored against content/sim/AUTHORING.md by a schema-constrained author, then
 * checked by an adversarial safety verifier (two-tier boundary, capacity-event
 * boundary, never-command five, no-numbers, no-dominant-option, evidence labels,
 * voice) and repaired against its findings, then read in the rolling human review.
 * 12 records. Originally compiled from a JSON batch by tools/build-content.mjs;
 * that JSON was not retained, so THIS FILE is the authored artifact now and is
 * edited directly. Its shape stays JSON-compatible so tools/variant-hygiene.mjs
 * can keep rewriting it structurally.
 */
import type { SimEvent } from "@/content/sim/schema";

export const EVENTS_COMP_FAMILY: SimEvent[] = [
  {
    "id": "evt-diane-check-in",
    "family": "people",
    "domains": [
      "family",
      "relationships"
    ],
    "label": "Diane calls on a Sunday",
    "scene": "Diane calls on a Sunday, the way she does. She has a question about a form she could answer herself, and underneath it the actual question, which is where you are, and whether the apartment is warm, and whether you are eating.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-parent-diane"
    },
    "seasonBands": [
      [
        1,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-diane-real-version",
        "label": "Give her the real version",
        "chips": {
          "costs": [
            "most of an evening",
            "saying the parts you had trimmed out"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You tell her how the month actually went. She asks better questions than you expected and does not try to solve any of it.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "regulation": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You give her more than the usual summary. She worries at one part of it, and says before she calls off that there is money there if it comes to that.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "flagsSet": [
                  "diane-offer-open"
                ],
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-hand-her-the-task",
        "label": "Hand her the actual task",
        "chips": {
          "costs": [
            "a job you could have done yourself",
            "her way of doing it"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "gauge": "timeStructure",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "She takes the form off you and has it back by Wednesday, annotated. She says to send her the next one, and anything else that is going.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "flagsSet": [
                  "diane-offer-open"
                ],
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She does it her way, which is slower and more thorough than yours. You redo one part quietly and she never finds out.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 1,
            "outcome": {
              "line": "She says she will do it and then the week gets her. It arrives late, done properly, after you had already started again.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-diane-keep-it-short",
        "label": "Keep it short",
        "chips": {
          "costs": [
            "the call ends before the second question"
          ],
          "variance": "narrow",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:income-obligation",
              "text": "The evening is already spoken for, and she knows it is."
            }
          ]
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You answer the form question, say the apartment is fine, and get your evening back. Nothing between you moves in either direction.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "She hears the shape of the call before it ends and lets you go early. The evening is yours and slightly less usable than it was.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "She stays on the line well past the point either of you had set aside for it, and neither of you moves to end it.",
        "It is the best of these calls in a long while. Neither of you says so, and both of you notice."
      ],
      "solid": [
        "The call runs long and lands nowhere in particular. She calls again the following Sunday.",
        "You talk about the neighbors and the car and almost nothing that matters. She sounds better afterwards, and so do you."
      ],
      "mixed": [
        "The call does what these calls do and no more. She says goodbye first, which is not usually the order of it.",
        "You get off the phone having taken the shorter way through it. So did she, and she got there first."
      ]
    },
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 3
  },
  {
    "id": "evt-diane-quiet",
    "family": "people",
    "domains": [
      "family",
      "relationships"
    ],
    "label": "The Sunday calls stop",
    "scene": "The Sunday calls have stopped arriving. When you look, there is a message from a while back that you did not answer, and a photograph of the garden with no words attached. She has not said anything about it. She has just stopped being the one who starts.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-parent-diane"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-diane-ring-tonight",
        "label": "Ring her tonight",
        "chips": {
          "costs": [
            "an evening you had plans for"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "gauge": "connection",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 3,
            "outcome": {
              "line": "She picks up on the second ring and does not mention the gap. The conversation is a little formal and it takes the evening.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "timeStructure": -1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She is out. She calls back two days later, briefly, on her way somewhere. Something has moved, and not much of it.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-ask-for-something",
        "label": "Ask her for something specific",
        "chips": {
          "costs": [
            "admitting you need it",
            "whatever she sends back with it"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You ask her how she used to do the thing with the landlord. She talks for half an hour and starts ringing again the week after.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "She answers the question properly and stops there. It is warmer than the last three exchanges and it is still an answer to a question.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-leave-it",
        "label": "Leave it this season",
        "chips": {
          "costs": [
            "the gap gets one season longer"
          ],
          "variance": "narrow",
          "reversibility": "costly to undo"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You spend the season on the thing that could not wait. Nothing with Diane breaks and nothing with Diane moves.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The season goes by without a call. Neither of you marks the day it stops being an accident.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "neglect": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-diane-quiet-sets",
        "label": "The gap gets its own habit",
        "effects": {
          "relationships": [
            {
              "id": "arc-parent-diane",
              "quality": -1
            }
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "mixed"
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-diane-repair",
    "family": "people",
    "domains": [
      "family",
      "relationships",
      "repair"
    ],
    "label": "The silence on the line",
    "scene": "You said the thing you had been not saying: that you have been absent, and that you know it. She listened all the way through without filling the pauses. Now there is a silence on the line, and it is hers to do something with.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-parent-diane"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-diane-say-it-and-stop",
        "label": "Say it and stop talking",
        "chips": {
          "costs": [
            "the pause you would rather fill"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "She says she had noticed, and then asks about your week — which is how she puts a thing down once she has decided to.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "She thanks you for saying it and moves the conversation to the garden. Whether it landed is not something she is going to tell you tonight.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "She says she will think about it, and means both words. She does not ring for a while afterwards, and she does ring.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-turn-up-weekly",
        "label": "Turn up every week instead",
        "chips": {
          "costs": [
            "a standing evening, whether or not you feel like it",
            "the season's spare hours"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "gauge": "timeStructure",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You call every week for a season. She never once comments on it, and she is there every time, and by the end it is just a thing you both do.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "timeStructure": -1
                },
                "capability": {
                  "execution": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 2
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You keep it up for most of the season. The calls that happened happened; the ones that did not are not discussed.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Two good weeks, then the season takes the rest back. She answers every time you do ring and starts none of them.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-take-the-offer",
        "label": "Take her up on the offer",
        "chips": {
          "costs": [
            "accepting something you meant to refuse",
            "knowing roughly what it costs her"
          ],
          "variance": "wide",
          "reversibility": "costly to undo",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "This is not a spare offer. It is the only one."
            }
          ]
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "companionFlags": [
            "diane-offer-open"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "She has been holding it open for a long time. Watching her hand it over is the part that actually mends something.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "flagsClear": [
                  "diane-offer-open"
                ],
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She gives it, and then mentions twice what it cost her, and the mention sits in the room afterwards.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "flagsClear": [
                  "diane-offer-open"
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "She says yes and you can hear it is more than she has. You take less than was offered and neither of you says why.",
              "effects": {
                "flagsClear": [
                  "diane-offer-open"
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-diane-refuses",
    "family": "money",
    "domains": [
      "family",
      "money"
    ],
    "label": "She says no to the money",
    "scene": "You asked her for the money. She took a day and then said no, and did not say why. Straight afterwards she asked about your week, in exactly the same voice, as though the two things were not sitting in the same conversation.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-parent-diane"
    },
    "seasonBands": [
      [
        4,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-diane-take-the-no",
        "label": "Take the no",
        "chips": {
          "costs": [
            "the gap in the month is still a gap"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You say all right, and mean it, and ask about the garden. The no stays a no and the Sunday call survives it intact.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You say all right and something in your voice does not. She hears it, and lets it go past without picking it up.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-diane-ask-why",
        "label": "Ask her why",
        "chips": {
          "costs": [
            "pushing on a door she is holding"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She says it is not something she wants to go into, and holds there. You come away knowing where the edge of the subject is.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You ask twice and get the same sentence twice. The call ends earlier than these calls usually end.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-find-it-elsewhere",
        "label": "Find the money elsewhere",
        "chips": {
          "costs": [
            "a worse rate than hers",
            "a tighter run of months"
          ],
          "variance": "wide",
          "reversibility": "costly to undo",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "There was never a second name on this list to try."
            },
            {
              "when": "start:carrying-debt",
              "text": "Another line on top of the lines already running."
            }
          ]
        },
        "flags": [
          "recovery",
          "endurance"
        ],
        "supportLink": "/topics/money",
        "sensitivity": {
          "capability": "execution",
          "systemicFlags": [
            "coverage-gap"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You find a route that works. It costs more than hers would have and it is yours, which turns out to matter to you.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You cover the month by moving the shortfall into the next one. Nothing is solved and nothing collapses either.",
              "effects": {
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/money",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Diane declining is her decision, not a setback with a way back from it. The gap left in the month has its own route on this card; rendering a way on from her no would put her choice on the board as a problem to be solved."
    },
    "weight": 2
  },
  {
    "id": "evt-diane-deepen",
    "family": "people",
    "domains": [
      "family",
      "relationships"
    ],
    "label": "Something from her twenties",
    "scene": "She tells you something about her own twenties you had never heard — the job she walked out of, the apartment she moved into afterwards, how long it took her to get level again. It is not advice, and she is not asking you for anything. She just tells you.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-parent-diane"
    },
    "seasonBands": [
      [
        6,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-diane-ask-the-next-question",
        "label": "Ask the next question",
        "chips": {
          "costs": [
            "the rest of the evening"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 3,
            "outcome": {
              "line": "She keeps going for another hour. By the end you know a version of her that was never going to arrive on a Sunday call about forms.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She answers one more and then puts the lid back on, gently. What she did say does not get taken back.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-tell-her-yours",
        "label": "Tell her one of yours",
        "chips": {
          "costs": [
            "something she did not know",
            "her reaction to it"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You tell her the thing you had kept off the calls. She sits with it, says almost nothing, and rings the next day to say almost nothing again.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "regulation": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She takes it seriously and asks careful questions. The conversation is not comfortable and it does not go anywhere bad.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "She goes quiet and then practical, and starts solving it. It is not what you wanted from her and it is what she has to give.",
              "effects": {
                "capability": {
                  "regulation": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-let-it-sit",
        "label": "Let it sit where it is",
        "chips": {
          "costs": [
            "a door opened and not walked through"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You say something small and the conversation moves on. It stays true that she told you, and she knows she did. The evening is still yours.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The moment closes over. Neither of you mentions it again this season and the Sunday calls go back to being about forms.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-diane-withdraws",
    "family": "people",
    "domains": [
      "family",
      "relationships"
    ],
    "label": "The calls go formal",
    "scene": "The calls still happen. They are about the car insurance and the cousin's wedding, and they end on time. She has stopped asking where you are. When you offer to come down she says that would be nice, in the voice she keeps for the neighbors.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-parent-diane"
    },
    "seasonBands": [
      [
        6,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-diane-let-it-be-what-it-is",
        "label": "Let it be what it is",
        "chips": {
          "costs": [
            "the version you had in mind"
          ],
          "variance": "narrow",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You take the calls as they come and stop waiting for the other kind. It is a smaller relationship, and it is not nothing.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You keep the formal version running. The effort of it shows on both ends of the line and neither of you names it.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-name-it",
        "label": "Name it out loud",
        "chips": {
          "costs": [
            "hearing the answer"
          ],
          "variance": "moderate",
          "reversibility": "locks in"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You tell her you can feel the change. She says she is fine, twice, and asks about the insurance again. Saying it cost you nothing you still had.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She says she got tired of being the one who rang. She says it without heat, and she does not take it back afterwards.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-diane-keep-sending",
        "label": "Keep sending things anyway",
        "chips": {
          "costs": [
            "messages that get short answers",
            "being the one who starts, now"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You keep sending the photographs. She answers every one, briefly, and starts none. You are holding the door now, and you decide you can.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Some seasons you remember and some you do not. She never reminds you either way.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-parent-diane",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-parent-diane",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Diane has decided what size this is going to be, and says so in the only way she says things. A route back from another person's withdrawal would render her decision as damage waiting to be repaired, which is not what it is."
    },
    "negative": true,
    "weight": 1
  },
  {
    "id": "evt-tasha-call",
    "family": "people",
    "domains": [
      "family",
      "relationships"
    ],
    "label": "Tasha rings on speaker",
    "scene": "Tasha rings at an odd hour, on speaker, doing something else while she talks. Half of it is the family group chat and whose turn the birthday is. The other half is her own week, which she mentions once and then moves straight past.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-sibling-tasha"
    },
    "seasonBands": [
      [
        1,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-tasha-take-the-birthday",
        "label": "Take the birthday this time",
        "chips": {
          "costs": [
            "an errand, a card, and remembering the date"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You do it, and it arrives on time, and she says nothing about it beyond a thumbs-up. She stops being the only one who tracks these.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You take it and it goes out late but it goes out. She amends the date in the shared calendar without comment.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-go-back-to-her-week",
        "label": "Go back to what she mentioned",
        "chips": {
          "costs": [
            "staying on the call past the admin"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "She takes the speaker off and tells you the actual size of it. You are being talked to as an adult, possibly for the first time.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She says it is fine and steers back to the family admin. The door was open for about a minute and you did knock.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-tasha-stay-on-admin",
        "label": "Stay on the admin",
        "chips": {
          "costs": [
            "the call ends where it started"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You settle the birthday, the parents' thing, and the date in June. Efficient, brief, and both of your evenings survive it.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The call is logistics from end to end. She calls off having said nothing about herself, which she notes somewhere and does not raise.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "You are still on the phone when her hands are free again, and she does not hang up.",
        "The call goes somewhere neither of you had planned for it to go, and both of you stay for that part."
      ],
      "solid": [
        "The call ends when her hands are free again. Nothing is settled and you are both in contact, which is the usual state of it.",
        "You talk over each other for a while and sort out one thing. She calls off mid-sentence, which is how she calls off."
      ],
      "mixed": [
        "The call ends where it started, on speaker, with the half that was not admin still unsaid.",
        "You settle the logistics and nothing else. She is on to the next thing before the call has properly ended."
      ]
    },
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 3
  },
  {
    "id": "evt-tasha-imbalance",
    "family": "home",
    "domains": [
      "family",
      "caregiving",
      "home"
    ],
    "label": "Tasha stops asking",
    "scene": "You notice Tasha has stopped asking. The last three things that needed doing at home got done, and nobody rang you about any of them. In the group chat she answers about logistics, on time, and about nothing else.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-sibling-tasha"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-tasha-take-one-off-her",
        "label": "Take one off her",
        "chips": {
          "costs": [
            "a weekend and the fare",
            "an office that never picks up"
          ],
          "variance": "moderate",
          "reversibility": "reversible",
          "positionNotes": [
            {
              "when": "start:place-bound",
              "text": "Getting there and back eats most of what you were spending."
            }
          ]
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "constraintFlags": [
            "start:place-bound"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You take the appointment and the paperwork behind it. She sends the details and nothing else, and the details are complete.",
              "effects": {
                "skills": [
                  "caregiving"
                ],
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "You take it, and it runs long in the way she never mentioned it running long. You get it done and it costs the weekend after as well.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-ask-what-she-carries",
        "label": "Ask what she is carrying",
        "chips": {
          "costs": [
            "hearing the whole list"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She lists it, flatly, and asks for nothing at the end. It takes longer than you had set aside for the call.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She says it is fine and that she has it. You can hear that both halves of that are true at once.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-tasha-propose-a-schedule",
        "label": "Propose a standing schedule",
        "chips": {
          "costs": [
            "a fixed obligation every month",
            "the seasons you have already promised elsewhere"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "execution",
          "gauge": "timeStructure",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "The schedule holds. It costs you a fixed weekend a month, and after the first round nobody has to arrange anything, which was the part she minded.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "capability": {
                  "execution": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 3,
            "outcome": {
              "line": "It runs for a season and then a month goes past. She picks that month up without mentioning that she has.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-tasha-ledger-carries",
        "label": "The list you heard and left where it was",
        "effects": {
          "relationships": [
            {
              "id": "arc-sibling-tasha",
              "quality": -1
            }
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "mixed"
        ]
      },
      {
        "id": "de-tasha-schedule-settles",
        "label": "The month that no longer needs arranging",
        "effects": {
          "gauge": {
            "timeStructure": 1
          },
          "relationships": [
            {
              "id": "arc-sibling-tasha",
              "quality": 1
            }
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "strong"
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-tasha-repair",
    "family": "home",
    "domains": [
      "family",
      "caregiving",
      "repair"
    ],
    "label": "You took the turn",
    "scene": "You took the turn — the appointment, the two afternoons, the phone calls with an office that never picks up. Tasha knows you did it. She has not said anything about it, and the group chat carries on as though the week ran itself.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-sibling-tasha"
    },
    "seasonBands": [
      [
        2,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-tasha-dont-mention-it",
        "label": "Do not mention it",
        "chips": {
          "costs": [
            "not being told it counted"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "Weeks later she asks you for something small. Being asked, from her, is the receipt.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Nothing is said. The next turn comes round and it is hers, and it goes more easily than the last one did.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-say-the-ledger",
        "label": "Say the ledger should be even",
        "chips": {
          "costs": [
            "naming the thing she keeps quietly"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She says she is not keeping score, and then tells you the score. Having it out loud is a relief to both of you.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She says she would rather not do this as a conversation. The turn you took still counted; the conversation about it did not.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-take-the-next-one",
        "label": "Take the next one too",
        "chips": {
          "costs": [
            "another month of it",
            "the thing of yours that slips"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "gauge": "healthEnergy",
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You take the next one before it is offered. She stops calling them favours, and starts sending you the things she used to handle alone.",
              "effects": {
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "caregiving"
                ],
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 2
                  }
                ],
                "maintenanceDebt": 1
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You take it and something of yours gives — the reading, the sleep, the apartment. You know the office and the paperwork now, and she does not know about the rest.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "skills": [
                  "caregiving"
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-tasha-refuses",
    "family": "home",
    "domains": [
      "family",
      "caregiving"
    ],
    "label": "She says it is your turn",
    "scene": "You ask Tasha to cover the thing at home this month. She says no. She says it is your turn, which it is, and that she is out of room anyway. She does not soften it, and she does not explain what out of room means.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-sibling-tasha"
    },
    "seasonBands": [
      [
        3,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-tasha-take-your-turn",
        "label": "Take your turn",
        "chips": {
          "costs": [
            "the weekend, and what you had planned for it"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You do it, badly at first and then adequately. Nobody thanks you and nobody mentions it afterwards.",
              "effects": {
                "skills": [
                  "caregiving"
                ],
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You do it and it takes more of the month than you had set aside. The month absorbs it and something else gets moved.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-ask-what-she-meant",
        "label": "Ask what she meant",
        "chips": {
          "costs": [
            "a question she owes no answer to"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She tells you a little of her own month — the money part, briefly, and none of the rest. It reframes about a year of things.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She says she would rather not, and asks about your week instead. The subject is closed and the call is not.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-tasha-arrange-it-another-way",
        "label": "Arrange it another way",
        "chips": {
          "costs": [
            "paying someone, or owing a neighbor"
          ],
          "variance": "wide",
          "reversibility": "costly to undo",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "There is no third person on this list to ring."
            }
          ]
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "gauge": "money",
          "systemicFlags": [
            "waitlist"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You find a way that needs neither of you — paid, arranged, and steady enough to leave running. It costs money you would rather have kept.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": 1
                },
                "conditionsClear": [
                  "caring-duty"
                ],
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The arrangement half-works. You are back on the phone about it twice, and it costs the money anyway.",
              "effects": {
                "gauge": {
                  "money": -1
                }
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Tasha saying no and holding a limit she has every right to hold is not a setback, and there is nothing to be recovered from it. What still needs covering at home has its own route on this card; her refusal does not get one."
    },
    "weight": 2
  },
  {
    "id": "evt-tasha-deepen",
    "family": "people",
    "domains": [
      "family",
      "relationships"
    ],
    "label": "A weekend with no reason",
    "scene": "Tasha comes to yours for a weekend with no family reason attached. Somewhere on the second evening the conversation stops being about your parents and becomes about her job, and your job, and the fact that you are both now people with jobs and rent.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-sibling-tasha"
    },
    "seasonBands": [
      [
        7,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-tasha-tell-her-where-you-are",
        "label": "Tell her where you actually are",
        "chips": {
          "costs": [
            "the state of the month, said out loud"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "regulation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You tell her the real state of it. She tells you hers, which is tighter than she has ever let on, and the two of you sit in that a while.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You tell her most of it. She takes it seriously and does not offer to fix any of it, which is what you wanted and could not have asked for.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-make-it-standing",
        "label": "Make it a standing weekend",
        "chips": {
          "costs": [
            "a weekend a season, held",
            "the fare, each time"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "execution",
          "gauge": "timeStructure",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "It becomes a fixed thing in both calendars. The sibling admin moves off the group chat and into a weekend that is not about admin.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "timeStructure": -1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "It happens twice and then a season goes by. Both of you still refer to it as a thing you do.",
              "effects": {
                "gauge": {
                  "connection": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The dates keep moving. You end up with a shorter version of it, in a station café, and it is still better than the group chat.",
              "effects": {}
            }
          }
        ]
      },
      {
        "id": "opt-tasha-keep-it-light",
        "label": "Keep the weekend light",
        "chips": {
          "costs": [
            "the deeper conversation stays unopened"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You cook badly, watch something long, and it is easy in a way the two of you have not managed since school.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1,
                  "connection": 1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "A good weekend, and neither of you says the thing you both brought with you. She goes home on the early train.",
              "effects": {
                "gauge": {
                  "healthEnergy": 1
                }
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "weight": 2
  },
  {
    "id": "evt-tasha-steps-back",
    "family": "home",
    "domains": [
      "family",
      "caregiving",
      "home"
    ],
    "label": "Tasha steps back",
    "scene": "Tasha tells you she is stepping back from the family admin. All of it, not just this month. She is not angry about it. She says she has been thinking about it for a long time, that she will answer if you ring, and mutes the group chat.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-sibling-tasha"
    },
    "seasonBands": [
      [
        7,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-tasha-let-her-go",
        "label": "Let her go",
        "chips": {
          "costs": [
            "the half of it that was hers"
          ],
          "variance": "moderate",
          "reversibility": "locks in"
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You say all right, and that you will pick up what she is putting down. The call ends kindly, and it ends.",
              "effects": {
                "capability": {
                  "regulation": 1,
                  "adaptability": 1
                },
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You say all right and then spend the evening working out what she used to do. It is more than you had thought it was.",
              "effects": {
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "exit": true
                  }
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-ask-for-the-two-of-you",
        "label": "Ask about the two of you",
        "chips": {
          "costs": [
            "asking a question with no good answer available"
          ],
          "variance": "wide",
          "reversibility": "locks in"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "She says the family thing and the two of you are separate things, and that she meant the family thing. She does not promise a shape for the rest.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She says she does not know yet and would rather not decide it on a phone call. Then she asks about your week, and means that part.",
              "effects": {
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "exit": true
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-take-the-list",
        "label": "Take the whole list",
        "chips": {
          "costs": [
            "everything she was doing, now yours",
            "the months it will run for"
          ],
          "variance": "moderate",
          "reversibility": "locks in",
          "positionNotes": [
            {
              "when": "start:caring-duty",
              "text": "This lands on top of what you already carry, not beside it."
            }
          ]
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "execution",
          "gauge": "timeStructure",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You ask her to send the list. It is longer than the version you had in your head, and from this season it is yours.",
              "effects": {
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "caregiving"
                ],
                "conditionsSet": [
                  "caring-duty"
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "exit": true
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You take it and it runs the season. Some of it does not get done, and nobody rings about that either.",
              "effects": {
                "conditionsSet": [
                  "caring-duty"
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "exit": true
                  }
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Tasha is putting the family admin down on purpose, after a long time thinking about it, and she says as much. There is no way back from a person's own decision, and offering one here would read as an attempt to undo it."
    },
    "negative": true,
    "weight": 1
  }
];
