/**
 * Event batch "world-late" — GENERATED by tools/build-content.mjs from events-world-late.json.
 *
 * Authored against content/sim/AUTHORING.md by a schema-constrained author, then
 * checked by an adversarial safety verifier (two-tier boundary, capacity-event
 * boundary, never-command five, no-numbers, no-dominant-option, evidence labels,
 * voice) and repaired against its findings, then read in the rolling human review.
 * 10 records. Originally compiled from a JSON batch by tools/build-content.mjs;
 * that JSON was not retained, so THIS FILE is the authored artifact now and is
 * edited directly. Its shape stays JSON-compatible so tools/variant-hygiene.mjs
 * can keep rewriting it structurally.
 */
import type { SimEvent } from "@/content/sim/schema";

export const EVENTS_WORLD_LATE: SimEvent[] = [
  {
    "id": "evt-the-restructure-lands",
    "family": "work",
    "domains": [
      "work",
      "institutions",
      "income"
    ],
    "label": "The restructure lands",
    "scene": "An all-hands called at short notice, a slide with boxes on it, and your box is one of the ones with a question mark. Your manager cannot say more today. The room empties into the corridor and everyone starts doing the same arithmetic.",
    "trigger": {
      "kind": "scheduled",
      "seasonIndex": 15
    },
    "seasonBands": [
      [
        14,
        22
      ]
    ],
    "options": [
      {
        "id": "opt-restructure-reapply",
        "label": "Reapply for your own job",
        "chips": {
          "costs": [
            "evenings spent proving what you already do",
            "the sting of being asked to"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "systemicFlags": [
            "restructure",
            "headcount-freeze"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You keep the seat. The title survives and the remit does not — you come out doing more of what the organisation still funds.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "survived-restructure"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You keep the job and lose the part of it you liked. Nobody says that out loud, and it is what happened.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "timeStructure": -1
                },
                "capability": {
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The panel goes to someone from the other team. You are given a date, a form, and an address to return the laptop to.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "between-jobs"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-restructure-take-exit",
        "label": "Take the exit package",
        "chips": {
          "costs": [
            "income with a stop date on it",
            "the plan you had for this year"
          ],
          "variance": "wide",
          "reversibility": "locks in",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "A runway with nothing underneath it is a shorter runway."
            },
            {
              "when": "start:income-obligation",
              "text": "Someone else is counting on the month after the payout runs out."
            }
          ]
        },
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:no-backstop",
            "start:income-obligation"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "The payout lands and you are out clean, with a stretch of months you get to spend rather than a manager who spends them for you.",
              "effects": {
                "gauge": {
                  "money": 2,
                  "timeStructure": 1
                },
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "between-jobs"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You take it. The money is real and shorter than it looked, and days without a shape are harder than you expected them to be.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "between-jobs"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "You sign, and the market you sign into is the one everyone else from the building is also in, with the same year on the same page.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "connection": -1
                },
                "flagsSet": [
                  "between-jobs"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-restructure-look-now",
        "label": "Start looking, quietly",
        "chips": {
          "costs": [
            "a job search stacked on top of a job",
            "energy you do not currently have"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/situations/job-loss",
        "sensitivity": {
          "gauge": "connection",
          "capability": "socialNavigation",
          "systemicFlags": [
            "restructure"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You are three conversations in when the announcement finally comes, which turns out to be the whole difference.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "healthEnergy": -1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "has-options"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Nothing lands in time, but you learn what you are worth outside the building, which you did not know last season.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "adaptability": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "Someone mentions to someone that you have been asking around. The room you walk into on Monday is a slightly colder room.",
              "effects": {
                "gauge": {
                  "connection": -1,
                  "healthEnergy": -1
                },
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "Your name stays on the chart. Two of the names next to it do not, and the work those two were doing has to live somewhere now.",
        "They keep you and rewrite the box you sit in. Same desk, same badge, a job description you would not have applied for."
      ]
    },
    "readRef": "/situations/job-loss",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-work-sideways-move",
      "act-learn-retrain-pivot",
      "act-learn-depth-or-spread"
    ],
    "excludesFlags": [
      "between-jobs"
    ],
    "negative": true,
    "invalidates": {
      "actionIds": [
        "act-work-negotiate-pay",
        "act-work-promotion-trap"
      ],
      "resolution": "refund",
      "note": "The conversation you committed to has no one left to have it with, so what you put into it comes back to you."
    },
    "weight": 3
  },
  {
    "id": "evt-specialism-stops-paying",
    "family": "work",
    "domains": [
      "work",
      "skills",
      "markets"
    ],
    "label": "The specialism stops paying",
    "scene": "The thing you got good at is being quoted at less than it was, and the postings that used to name it now list it as one line among six. Nobody sent a memo. You notice it in the way the work arrives, and in who stops calling.",
    "trigger": {
      "kind": "consequence",
      "sourceRef": "act-wait"
    },
    "seasonBands": [
      [
        15,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-specialism-go-deeper",
        "label": "Go deeper into the narrow thing",
        "chips": {
          "costs": [
            "hours on something fewer people want",
            "the years you are betting on it"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "skill": "deep-practice",
          "capability": "learning",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 1,
            "outcome": {
              "line": "The market thins and you are still standing in it. Fewer buyers, and the ones left pay properly for the last person who can do this.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "deep-practice"
                ],
                "flagsSet": [
                  "scarce-skill"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You get better at it. Better at it is not the same as needed, and this season does not tell you which one you are.",
              "effects": {
                "capability": {
                  "learning": 1
                },
                "skills": [
                  "deep-practice"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "You spend the season sharpening a tool the work has stopped asking for, and the seasons you spent are not returnable.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-specialism-step-sideways",
        "label": "Learn the thing next to it",
        "chips": {
          "costs": [
            "being a beginner again at your age",
            "a course, or the time to fake one"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "flags": [
          "recovery"
        ],
        "sensitivity": {
          "capability": "adaptability",
          "gauge": "timeStructure",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "The adjacent thing turns out to be mostly your thing wearing different words. You are useful in the new conversation by spring.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "adaptability": 1,
                  "learning": 1
                },
                "skills": [
                  "adjacent-craft"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Halfway competent at the new thing, still the best in the room at the old one. Neither is a position yet.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "skills": [
                  "adjacent-craft"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-specialism-follow-the-work",
        "label": "Move to where it still pays",
        "chips": {
          "costs": [
            "a deposit and a van",
            "everyone you know is here"
          ],
          "variance": "wide",
          "reversibility": "locks in",
          "positionNotes": [
            {
              "when": "start:place-bound",
              "text": "What holds you here does not move when you do."
            },
            {
              "when": "start:caring-duty",
              "text": "The duty travels with you, or it does not travel at all."
            }
          ]
        },
        "sensitivity": {
          "constraintFlags": [
            "start:place-bound",
            "start:caring-duty"
          ],
          "gauge": "money",
          "strength": 0.7
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "The same skill, the same you, a different market. The rate is what it used to be here and the work is not scarce.",
              "effects": {
                "gauge": {
                  "money": 2,
                  "connection": -1
                },
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "relocated"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The work is there. So is the rent, and a winter of knowing nobody's phone number.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "connection": -2
                },
                "flagsSet": [
                  "relocated"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "You arrive and the market you moved for has already started doing what your old one did. Now you are far away as well.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "connection": -2
                },
                "flagsSet": [
                  "relocated"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "The overlap is larger than the difference. By spring you are the one in the room who can speak both, and both sides start routing through you.",
        "Six weeks of feeling stupid, and then it goes in. What you already knew turns out to have been most of the way there."
      ]
    },
    "readRef": "/topics/work",
    "evidenceLabel": "contested",
    "recoveryRefs": [
      "act-work-field-shifting",
      "act-learn-depth-or-spread",
      "act-learn-retrain-pivot"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-former-colleague-hiring",
    "family": "work",
    "domains": [
      "work",
      "relationships",
      "opportunity"
    ],
    "label": "A former colleague is hiring",
    "scene": "Ray left the building two years ago and turns up in your messages with a role and a sentence about how it is a mess, but a good mess. There is no posting yet. Ray wants an answer before it becomes a posting.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-coworker-ray"
    },
    "seasonBands": [
      [
        16,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-ray-take-conversation",
        "label": "Take the conversation",
        "chips": {
          "costs": [
            "a half day you have to account for",
            "the risk of wanting it"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "companionFlags": [
            "ray-vouches"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "It is the job Ray said it was. You go in known rather than screened, which is a different door into the same building.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "connection": 1
                },
                "flagsSet": [
                  "has-options"
                ],
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "stageDelta": 1,
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Good mess, accurate description. You come away with a real picture and no decision, and Ray says the door stays open a while.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The role is smaller than the sentence about it. You have spent a day and some of Ray's goodwill finding that out.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "neglect": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-decline-plainly",
        "label": "Say no, and say why",
        "chips": {
          "costs": [
            "a door you are choosing not to open"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Ray takes the no without argument and asks you to say if that changes. The line stays open because you did not waste it.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Ray hears it as a no to Ray. It is civil afterwards, and slightly less than it was.",
              "effects": {
                "gauge": {
                  "connection": -1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-ray-put-someone-forward",
        "label": "Put someone else forward",
        "chips": {
          "costs": [
            "your name attached to their performance"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "gauge": "connection",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "They get it and they are good at it. Two people now think of you as the person who made that happen.",
              "effects": {
                "gauge": {
                  "connection": 2
                },
                "flagsSet": [
                  "knows-the-route"
                ],
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "stageDelta": 1,
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "They take the interview and it does not go anywhere. Nobody blames you and everybody remembers who suggested it.",
              "effects": {
                "gauge": {
                  "connection": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "They get it, and by autumn Ray is asking you, carefully, what you actually knew about how they work.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-coworker-ray",
                    "neglect": 2
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "recoveryRefs": [
      "act-work-sideways-move",
      "act-work-negotiate-pay",
      "act-work-manage-the-report"
    ],
    "weight": 2
  },
  {
    "id": "evt-building-is-being-sold",
    "family": "home",
    "domains": [
      "home",
      "housing",
      "money"
    ],
    "label": "The building is being sold",
    "scene": "A letter on good paper, addressed to the occupier. The owner is selling, viewings start next month, and nothing about you is mentioned because nothing about you is the point. The kitchen tap still drips and now nobody is going to come and fix it.",
    "trigger": {
      "kind": "systemic"
    },
    "seasonBands": [
      [
        13,
        22
      ]
    ],
    "options": [
      {
        "id": "opt-building-move-first",
        "label": "Move before you are moved",
        "chips": {
          "costs": [
            "a deposit you have to find twice over",
            "a month of boxes"
          ],
          "variance": "moderate",
          "reversibility": "locks in",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "Two deposits at once is the whole problem, and there is no float."
            }
          ]
        },
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:no-backstop",
            "start:stable-housing"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You go on your own schedule, to somewhere you chose rather than somewhere that was left. It costs most of what you had put by.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": 1
                },
                "capability": {
                  "execution": 1
                },
                "conditionsClear": [
                  "unstable-housing"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "The new place is further out and costs the same. The commute is now a thing you have instead of an hour you had.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "conditionsSet": [
                  "commute-heavy"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "You take the first thing that will have you at that speed, and you find out in November what was wrong with it.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "healthEnergy": -1
                },
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-building-sit-tight",
        "label": "Sit tight and wait for notice",
        "chips": {
          "costs": [
            "living in someone else's schedule",
            "strangers walking through your rooms"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "capability": "regulation",
          "systemicFlags": [
            "landlord-selling"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The buyer wants tenants in place. Nothing changes except the name on the standing order and the tap, which still drips.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Months of viewings and not knowing. You keep the apartment and spend the season unable to plan anything that starts after spring.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "failure",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The sale completes and the notice is the legal minimum. You are looking for somewhere in the worst month to be looking.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "conditionsSet": [
                  "unstable-housing"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-building-get-it-in-writing",
        "label": "Get the position in writing",
        "chips": {
          "costs": [
            "an afternoon of forms and phone queues",
            "a season spent waiting on other people's departments"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "skill": "logistics",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You get the notice period, the deposit route, and the agent's name in an email. None of it stops the sale and all of it stops the guessing.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "logistics"
                ],
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Two departments, one answer each, and they do not agree. You write down both and keep the email.",
              "effects": {
                "gauge": {
                  "timeStructure": -1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "The written answer takes until March to arrive. The apartments you would have been looking at in that stretch went to people who were looking.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": -1
                },
                "conditionsSet": [
                  "unstable-housing"
                ],
                "flagsSet": [
                  "knows-the-route"
                ]
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-notice-arrives",
        "label": "The notice arrives on the new owner's schedule",
        "effects": {
          "gauge": {
            "money": -1,
            "timeStructure": -1
          },
          "conditionsSet": [
            "unstable-housing"
          ]
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "failure"
        ]
      }
    ],
    "readRef": "/topics/money",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-housing-move-back",
      "act-housing-commute-trade",
      "act-housing-landlord-repair"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-lump-sum-and-a-bill",
    "family": "money",
    "domains": [
      "money",
      "tax",
      "planning"
    ],
    "label": "A lump sum, and a bill",
    "scene": "Backdated pay, all of it arriving in one month. It looks like more than it is: the withholding treats a lump as a lump rather than as your year, and whether it took enough is a question that keeps quiet until the spring you file.",
    "trigger": {
      "kind": "chance"
    },
    "seasonBands": [
      [
        14,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-lump-set-aside",
        "label": "Set aside what is owed",
        "chips": {
          "costs": [
            "the version of this where it was all yours"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "skill": "budgeting",
          "capability": "execution",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 4,
            "outcome": {
              "line": "You put the owed part somewhere you cannot reach it easily. The rest is smaller and entirely yours.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "execution": 1
                },
                "skills": [
                  "budgeting"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You set aside roughly the right amount, based on a figure a website gave you. Roughly right turns out to be most of the job.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "skills": [
                  "budgeting"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lump-clear-the-debt",
        "label": "Clear the debt with it",
        "chips": {
          "costs": [
            "the tax that has not asked yet"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo",
          "positionNotes": [
            {
              "when": "start:carrying-debt",
              "text": "This is the first time the balance has been within reach."
            }
          ]
        },
        "sensitivity": {
          "constraintFlags": [
            "start:carrying-debt"
          ],
          "gauge": "money",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "The balance goes. What it was quietly costing you every month stops costing you, and keeps not costing you.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "healthEnergy": 1
                },
                "flagsClear": [
                  "carrying-balance"
                ],
                "maintenanceDebt": -1
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "Most of the balance goes. The rest of it, and whatever the withholding did not cover, are now the same problem.",
              "effects": {
                "gauge": {
                  "money": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "You clear one obligation using money that already belonged to another one. Nothing is wrong yet.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "flagsSet": [
                  "tax-owed"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-lump-buy-the-unblock",
        "label": "Buy the thing that unblocks you",
        "chips": {
          "costs": [
            "the whole sum, at once",
            "no float afterwards"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "adaptability",
          "constraintFlags": [
            "start:place-bound"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "The car, the tools, the deposit — whatever the bottleneck was, it is not the bottleneck now, and the season opens up behind it.",
              "effects": {
                "gauge": {
                  "timeStructure": 1,
                  "money": -1
                },
                "capability": {
                  "execution": 1
                },
                "flagsSet": [
                  "unblocked"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "It helps, about as much as you hoped and not more. The money is gone and something is genuinely easier.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "timeStructure": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "It is spent, it was not the bottleneck, and the shortfall turns up in spring against an account that is already empty.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "flagsSet": [
                  "tax-owed"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "solid": [
        "The account with the boring name gets the tax share on the day the money lands, and stops being a decision.",
        "You work out what is not yours before you look at what is. What is left is a smaller number, and all of it survives the spring."
      ]
    },
    "delayedEffects": [
      {
        "id": "de-the-bill-catches-up",
        "label": "The spring filing catches up with the lump",
        "effects": {
          "gauge": {
            "money": -2
          },
          "maintenanceDebt": 1
        },
        "due": {
          "seasons": 2
        },
        "onBands": [
          "poor"
        ]
      }
    ],
    "readRef": "/topics/money",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-money-file-your-taxes",
      "act-money-debt-order"
    ],
    "weight": 2
  },
  {
    "id": "evt-recruiter-has-your-number",
    "family": "work",
    "domains": [
      "work",
      "market",
      "negotiation"
    ],
    "label": "A recruiter has your number",
    "scene": "A message that uses your job title correctly and your name almost correctly. Someone is paying them to find people like you, which is information about the market whether or not you want the job at the end of it.",
    "trigger": {
      "kind": "chance"
    },
    "seasonBands": [
      [
        13,
        22
      ]
    ],
    "options": [
      {
        "id": "opt-recruiter-run-the-process",
        "label": "Run the whole process",
        "chips": {
          "costs": [
            "four rounds and a take-home exercise",
            "annual leave spent on interviews"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "execution",
          "gauge": "healthEnergy",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "An offer, written down, better than what you have. Whatever you do next, you now do it from a position rather than a hope.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "capability": {
                  "socialNavigation": 1
                },
                "flagsSet": [
                  "has-options"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You get to the final round and they go with the internal candidate. You are sharper at this than you were in spring.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1
                },
                "capability": {
                  "socialNavigation": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "The role is put on hold after the take-home exercise. Nobody tells you; you work it out from the silence.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "timeStructure": -1
                },
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-recruiter-one-call",
        "label": "Take one call, no more",
        "chips": {
          "costs": [
            "twenty minutes and a straight answer"
          ],
          "variance": "narrow",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "strength": 0.4
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You come off the call knowing what your title is worth elsewhere this year. The number goes in your notes and Monday is the same Monday.",
              "effects": {
                "capability": {
                  "adaptability": 1
                },
                "flagsSet": [
                  "knows-the-rate"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "They are vague about the client and specific about your availability. You learn a little, mostly about recruiters.",
              "effects": {
                "capability": {
                  "socialNavigation": 1
                }
              }
            }
          }
        ]
      },
      {
        "id": "opt-recruiter-take-it-inside",
        "label": "Use it to open a conversation",
        "chips": {
          "costs": [
            "being the person who is looking",
            "one card you cannot play twice"
          ],
          "variance": "wide",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "systemicFlags": [
            "headcount-freeze",
            "restructure"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "They move on money rather than lose you, and it is in writing by the end of the month.",
              "effects": {
                "gauge": {
                  "money": 2
                },
                "capability": {
                  "socialNavigation": 1
                }
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You get warm words, a review date, and no number. The words cost them nothing and you have spent something.",
              "effects": {
                "gauge": {
                  "connection": -1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "Nothing moves, and you are now filed as someone with one foot outside. Next year's interesting work goes elsewhere.",
              "effects": {
                "gauge": {
                  "connection": -1,
                  "money": -1
                },
                "flagsSet": [
                  "flagged-as-leaving"
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "recoveryRefs": [
      "act-work-sideways-move",
      "act-work-exit-good-tired"
    ],
    "weight": 2
  },
  {
    "id": "evt-mo-leaves-the-city",
    "family": "people",
    "domains": [
      "relationships",
      "distance",
      "inner"
    ],
    "label": "Mo is leaving the city",
    "scene": "Mo tells you over the phone, in the middle of something else, like it had already been decided for a while. A job, a partner, cheaper rent — the reasons are good. The last easy Tuesday you had together has already happened and you did not notice it.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-friend-mo"
    },
    "seasonBands": [
      [
        14,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-mo-help-with-the-move",
        "label": "Help with the move",
        "chips": {
          "costs": [
            "a weekend and a hired van",
            "your back, on the Sunday"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "gauge": "connection",
          "capability": "vitality",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Two days of boxes and bad coffee. Mo goes anyway, and the going has your fingerprints on it rather than a gap.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "healthEnergy": -1,
                  "money": -1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "label": "Mo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You do the lifting and neither of you says the thing. The van pulls off and it is not said.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "money": -1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-say-the-true-thing",
        "label": "Say the true thing first",
        "chips": {
          "costs": [
            "saying it out loud to someone who is leaving"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "gauge": "connection",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "You tell Mo what the friendship has been. Mo takes it in, and says something back that you will keep.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "capability": {
                  "regulation": 1
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "label": "Mo",
                    "quality": 1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "stageDelta": 1,
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "It comes out clumsily and slightly too late. Mo hears the shape of it, which is not nothing, and still goes.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "outcome": {
              "line": "Mo says there is no room for this the week before a move, and means it. The saying of it stands where you left it, and the last conversation is a careful one.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "repair": 1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-mo-let-it-go-quietly",
        "label": "Let it go quietly",
        "chips": {
          "costs": [
            "nothing this season",
            "the thread, over the next several"
          ],
          "variance": "narrow",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "strength": 0.3
        },
        "bands": [
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "You send the leaving-day message and mean it. The replies get slower on both sides after that, evenly, without anyone deciding.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "neglect": 1
                  }
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "You mean to write in the new year, and then at Easter, and do not. The new apartment turns up in someone else's photographs before you get to it.",
              "effects": {
                "gauge": {
                  "connection": -2
                },
                "relationships": [
                  {
                    "id": "arc-friend-mo",
                    "label": "Mo",
                    "quality": -1
                  }
                ],
                "companions": [
                  {
                    "arcId": "arc-friend-mo",
                    "neglect": 2
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "readRef": "/topics/relationships",
    "evidenceLabel": "illustrative",
    "noRecoveryTie": {
      "reason": "Mo decided to go, and another person's decision is not a setback with a way out of it. The thread going quiet afterwards is a real cost and still not a failure state, so this card names no route back to a friend who chose to leave."
    },
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-tasha-asks-you-to-co-sign",
    "family": "money",
    "domains": [
      "money",
      "family",
      "liability"
    ],
    "label": "Tasha asks you to co-sign",
    "scene": "Tasha has found an apartment and the landlord wants a guarantor. She asks carefully, the way people ask for something they have already decided they need. If she misses a month, the letter comes to you, and she says that part out loud herself.",
    "trigger": {
      "kind": "companion",
      "arcRef": "arc-sibling-tasha"
    },
    "seasonBands": [
      [
        13,
        20
      ]
    ],
    "options": [
      {
        "id": "opt-tasha-sign-it",
        "label": "Sign it",
        "chips": {
          "costs": [
            "a year of someone else's rent, on paper",
            "the part that only shows up if it goes wrong"
          ],
          "variance": "wide",
          "reversibility": "locks in",
          "positionNotes": [
            {
              "when": "start:no-backstop",
              "text": "There is nobody standing behind you if this one comes back."
            }
          ]
        },
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:no-backstop",
            "start:carrying-debt"
          ],
          "companionFlags": [
            "tasha-steady"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "She gets the apartment and pays it every month. The signature costs you nothing but the knowing it is there.",
              "effects": {
                "gauge": {
                  "connection": 1
                },
                "flagsSet": [
                  "guarantor"
                ],
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "stageDelta": 1,
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "She gets the apartment. Every time her number comes up on your phone you check the date against the rent day first.",
              "effects": {
                "gauge": {
                  "connection": 1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "guarantor"
                ]
              }
            }
          },
          {
            "name": "failure",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "Winter goes badly for her hours. The letter with your name on it is polite and gives you fourteen days.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "guarantor"
                ],
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "label": "Tasha",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-say-no-once",
        "label": "Say no, once and clearly",
        "chips": {
          "costs": [
            "being the sibling who said no"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "gauge": "connection",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You give her the real reason instead of an excuse. She does not like it and she does not argue with it.",
              "effects": {
                "capability": {
                  "regulation": 1
                },
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "She says it is fine, in the voice people use when it is not fine yet. The call ends earlier than her calls usually end.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "capability": {
                  "regulation": 1
                }
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "outcome": {
              "line": "She stops bringing you things. Calls carry on and the subject of money is not in them any more.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "relationships": [
                  {
                    "id": "arc-sibling-tasha",
                    "label": "Tasha",
                    "quality": -1
                  }
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-tasha-offer-instead",
        "label": "Offer what you can instead",
        "chips": {
          "costs": [
            "a month of your own margin",
            "an ongoing conversation about money"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "sensitivity": {
          "gauge": "money",
          "skill": "budgeting",
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "You put in toward the deposit rather than your name on the lease. She takes it, and takes the smaller apartment.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "connection": 1
                },
                "companions": [
                  {
                    "arcId": "arc-sibling-tasha",
                    "repair": 1
                  }
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "She turns it down. What she needed was the signature, and the offer sits between you unspent.",
              "effects": {
                "capability": {
                  "regulation": 1
                }
              }
            }
          }
        ]
      }
    ],
    "delayedEffects": [
      {
        "id": "de-guarantee-is-called",
        "label": "The guarantee is called on",
        "effects": {
          "gauge": {
            "money": -2
          },
          "flagsSet": [
            "carrying-someone-elses-month"
          ],
          "maintenanceDebt": 1
        },
        "due": {
          "seasons": 4
        },
        "onBands": [
          "failure"
        ]
      }
    ],
    "readRef": "/topics/money",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-money-debt-order",
      "act-people-set-a-money-boundary",
      "act-money-cheap-or-lasting"
    ],
    "negative": true,
    "weight": 2
  },
  {
    "id": "evt-board-changes-requirements",
    "family": "civic",
    "domains": [
      "institutions",
      "credentials",
      "work"
    ],
    "label": "The board changes the requirements",
    "scene": "An email from the registering body, written by a committee. From next year the renewal needs hours you have not done, in a format that did not exist when you qualified. There is a transition arrangement, and nobody on the helpdesk can explain what it covers.",
    "trigger": {
      "kind": "scheduled",
      "seasonIndex": 18
    },
    "seasonBands": [
      [
        15,
        24
      ]
    ],
    "options": [
      {
        "id": "opt-board-do-the-hours",
        "label": "Do the new hours now",
        "chips": {
          "costs": [
            "a fee that is not small",
            "evenings and one whole weekend"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "learning",
          "gauge": "timeStructure",
          "systemicFlags": [
            "credential-inflation"
          ],
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 3,
            "outcome": {
              "line": "Done early, filed, confirmed. You are compliant before the rush, and the rush is when the places run out.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": -1
                },
                "capability": {
                  "learning": 1
                },
                "flagsSet": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "You do the hours and the format changes again in consultation. What you did still counts, mostly, and you keep the receipt.",
              "effects": {
                "gauge": {
                  "money": -1
                },
                "flagsSet": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "The provider you paid is not on the approved list when the list is published. The fee is not returnable.",
              "effects": {
                "gauge": {
                  "money": -2,
                  "healthEnergy": -1
                },
                "maintenanceDebt": 1
              }
            }
          }
        ]
      },
      {
        "id": "opt-board-wait-for-transition",
        "label": "Wait for the transition rule",
        "chips": {
          "costs": [
            "a year of not knowing where you stand"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "systemicFlags": [
            "credential-inflation",
            "waitlist"
          ],
          "capability": "adaptability",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "The transition arrangement lands and it covers people who qualified when you did. You spent nothing and lost nothing.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "flagsSet": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "The rule is published, it half covers you, and the half it does not cover is the half that takes longest.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "flagsSet": [
                  "partial-credential"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "No transition for your cohort. Everyone is booking the same courses at once, and the good ones are gone.",
              "effects": {
                "gauge": {
                  "money": -1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "waitlist"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-board-let-it-lapse",
        "label": "Let the registration lapse",
        "chips": {
          "costs": [
            "the door you paid to open, closing"
          ],
          "variance": "moderate",
          "reversibility": "locks in"
        },
        "sensitivity": {
          "gauge": "money",
          "constraintFlags": [
            "start:carrying-debt"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You were not using it. The fee stops, the evenings come back, and the work you actually do does not ask for it.",
              "effects": {
                "gauge": {
                  "money": 1,
                  "timeStructure": 1
                },
                "flagsSet": [
                  "lapsed-registration"
                ],
                "flagsClear": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 2,
            "outcome": {
              "line": "It lapses quietly. Two seasons later a posting you would have liked lists it as essential, and you read past it.",
              "effects": {
                "gauge": {
                  "money": 1
                },
                "flagsSet": [
                  "lapsed-registration"
                ],
                "flagsClear": [
                  "has-credential"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "Getting back on the register later means the new route in full, not the renewal. Nobody mentioned that at the time.",
              "effects": {
                "flagsSet": [
                  "lapsed-registration"
                ],
                "flagsClear": [
                  "has-credential"
                ],
                "maintenanceDebt": 1
              }
            }
          }
        ]
      }
    ],
    "readRef": "/map/credential-decision",
    "evidenceLabel": "evidence-informed",
    "recoveryRefs": [
      "act-learn-license-hours",
      "act-learn-employer-wont-fund",
      "act-work-field-shifting"
    ],
    "negative": true,
    "invalidates": {
      "actionIds": [
        "act-learn-certification-exam"
      ],
      "resolution": "convert",
      "convertTo": "act-wait",
      "note": "The course you committed to no longer counts toward the new requirement, so the commitment becomes a season of holding your position instead."
    },
    "weight": 2
  },
  {
    "id": "evt-someone-elses-work-is-yours",
    "family": "work",
    "domains": [
      "work",
      "responsibility",
      "relationships"
    ],
    "label": "Someone else's work is yours",
    "scene": "You are given a person. Not a title, not a raise — a person, whose output now appears under your name. He is competent on the days he is competent. Nobody has told you what you are allowed to do about the other days.",
    "trigger": {
      "kind": "scheduled",
      "seasonIndex": 18
    },
    "seasonBands": [
      [
        18,
        18
      ]
    ],
    "options": [
      {
        "id": "opt-responsible-manage-properly",
        "label": "Manage properly, on the record",
        "chips": {
          "costs": [
            "a standing hour every week",
            "writing things down that used to be assumed"
          ],
          "variance": "moderate",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "socialNavigation",
          "skill": "logistics",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "strong",
            "weight": 2,
            "outcome": {
              "line": "Clear expectations, written, and a weekly hour he can rely on. By spring he is doing the work and you are doing yours.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "capability": {
                  "socialNavigation": 1,
                  "execution": 1
                },
                "skills": [
                  "supervision"
                ],
                "flagsSet": [
                  "manages-someone"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "Some weeks he is fine and some weeks you are quietly redoing things at seven in the morning.",
              "effects": {
                "gauge": {
                  "timeStructure": -1,
                  "healthEnergy": -1
                },
                "skills": [
                  "supervision"
                ],
                "flagsSet": [
                  "manages-someone"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 1,
            "failure": true,
            "outcome": {
              "line": "He hears the written expectations as a file being built. The work does not improve and the room gets careful.",
              "effects": {
                "gauge": {
                  "connection": -1,
                  "healthEnergy": -1
                },
                "flagsSet": [
                  "manages-someone"
                ]
              }
            }
          }
        ]
      },
      {
        "id": "opt-responsible-cover-the-gaps",
        "label": "Cover the gaps yourself",
        "chips": {
          "costs": [
            "the hours nobody is counting",
            "your own work, done second"
          ],
          "variance": "moderate",
          "reversibility": "costly to undo"
        },
        "flags": [
          "endurance"
        ],
        "supportLink": "/threshold",
        "sensitivity": {
          "gauge": "healthEnergy",
          "capability": "vitality",
          "strength": 0.6
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "Nothing goes out wrong all season. Nobody above you knows why that took what it took, and he does.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "connection": 1
                },
                "flagsSet": [
                  "manages-someone"
                ],
                "maintenanceDebt": 1
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "It holds. Your own work is later than it used to be and nobody has said anything about that yet.",
              "effects": {
                "gauge": {
                  "healthEnergy": -1,
                  "timeStructure": -1
                },
                "flagsSet": [
                  "manages-someone"
                ],
                "maintenanceDebt": 1
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "Two months of absorbing it and something goes out wrong anyway, with your name on the version that shipped.",
              "effects": {
                "gauge": {
                  "healthEnergy": -2,
                  "connection": -1
                },
                "flagsSet": [
                  "manages-someone"
                ],
                "maintenanceDebt": 2
              }
            }
          }
        ]
      },
      {
        "id": "opt-responsible-hand-it-back",
        "label": "Say it is not yours",
        "chips": {
          "costs": [
            "being the one who raised it",
            "a conversation that goes on the record upward"
          ],
          "variance": "wide",
          "reversibility": "reversible"
        },
        "sensitivity": {
          "capability": "regulation",
          "systemicFlags": [
            "headcount-freeze",
            "restructure"
          ],
          "strength": 0.5
        },
        "bands": [
          {
            "name": "solid",
            "weight": 2,
            "outcome": {
              "line": "You put it plainly: responsibility without the authority to act on it. They agree, and give you the authority.",
              "effects": {
                "gauge": {
                  "timeStructure": 1
                },
                "capability": {
                  "regulation": 1
                },
                "flagsSet": [
                  "manages-someone",
                  "has-remit"
                ]
              }
            }
          },
          {
            "name": "mixed",
            "weight": 3,
            "outcome": {
              "line": "They agree it is unreasonable and there is nobody else. It stays with you, now formally acknowledged as unreasonable.",
              "effects": {
                "gauge": {
                  "timeStructure": -1
                },
                "flagsSet": [
                  "manages-someone"
                ]
              }
            }
          },
          {
            "name": "poor",
            "weight": 2,
            "failure": true,
            "outcome": {
              "line": "It is heard as not being able to handle it. The next thing that needs holding goes to someone else.",
              "effects": {
                "gauge": {
                  "connection": -1
                },
                "capability": {
                  "regulation": 1
                }
              }
            }
          }
        ]
      }
    ],
    "outcomeVariants": {
      "strong": [
        "The standing hour turns out to be the whole intervention. He knows what finished looks like now, and checks it against that before it reaches you.",
        "Written down, it stops being about him and starts being about the work. By spring you are reading his output instead of rebuilding it."
      ]
    },
    "readRef": "/topics/work",
    "evidenceLabel": "illustrative",
    "recoveryRefs": [
      "act-work-manage-the-report",
      "act-work-be-the-senior",
      "act-body-ask-accommodation"
    ],
    "weight": 2
  }
];
