/**
 * Generates content/sim/campaign/doors.ts from the authored chunk JSONs.
 *
 * The parse's Doors panel is the last thing a player reads after twenty-four
 * seasons. It used to render EVERY run flag as a door that "opened" — job ended,
 * benefits denied, reference burned, a friend asking for space — with the note
 * "This is available to you now" and the good-outcome color. This registry is the
 * authored meaning that replaced the guess: what each flag is called in the
 * player's language, and whether it opened, closed, or is still recoverable.
 *
 * A flag with no entry, or one marked skip, is NOT rendered as a door. The panel
 * only ever claims what someone wrote down.
 *
 * Run: node tools/gen-doors.mjs <dir-with-*.out.json>
 */
import fs from "node:fs";
import path from "node:path";

const DIR = process.argv[2];
if (!DIR) { console.error("usage: node tools/gen-doors.mjs <dir>"); process.exit(2); }

const STATES = new Set(["opened", "closed", "still recoverable"]);
const merged = {};
const errors = [];
for (const f of fs.readdirSync(DIR).filter((x) => x.endsWith(".out.json")).sort()) {
  const data = JSON.parse(fs.readFileSync(path.join(DIR, f), "utf8"));
  for (const [flag, v] of Object.entries(data)) {
    if (flag in merged) { errors.push(`${f}: duplicate entry for "${flag}"`); continue; }
    if (v.skip) { merged[flag] = { skip: true, why: String(v.why ?? "") }; continue; }
    if (!STATES.has(v.state)) { errors.push(`${f}: "${flag}" has state "${v.state}"`); continue; }
    if (!v.label || /\d/.test(v.label)) { errors.push(`${f}: "${flag}" has a bad label ${JSON.stringify(v.label)}`); continue; }
    merged[flag] = { label: String(v.label), state: v.state };
  }
}
if (errors.length) { errors.forEach((e) => console.error("REJECT " + e)); process.exit(1); }

const keys = Object.keys(merged).sort();
const body = keys
  .map((k) => {
    const v = merged[k];
    return v.skip
      ? `  ${JSON.stringify(k)}: { skip: true, why: ${JSON.stringify(v.why)} },`
      : `  ${JSON.stringify(k)}: { label: ${JSON.stringify(v.label)}, state: ${JSON.stringify(v.state)} },`;
  })
  .join("\n");

const file = `/**
 * THE DOOR REGISTRY — what each run flag means to the player, in their language.
 *
 * GENERATED by tools/gen-doors.mjs from authored chunks, then verified
 * adversarially. Edit the chunk sources and regenerate, or edit here and keep the
 * chunks in step.
 *
 * The parse's closing "Doors" panel used to push EVERY non-\`start:\` flag as
 * \`state: "opened"\` with the note "This is available to you now and was not at
 * eighteen" — and the stylesheet paints "opened" in the good-outcome color. So a
 * character who lost a job, was denied benefits or burned a reference read those
 * as green doors that opened, on the last screen of a twelve-year run. It also
 * printed the raw internal id. Blueprint §3.9 asks for three states; the build
 * shipped one.
 *
 * A flag with no entry here, or one marked \`skip\`, is not rendered as a door at
 * all. The panel only claims what someone wrote down.
 */

export type DoorMeaning =
  | { label: string; state: "opened" | "closed" | "still recoverable" }
  | { skip: true; why: string };

export const DOOR_MEANING: Record<string, DoorMeaning> = {
${body}
};

/** The note that renders under each state. Same voice as the rest of the parse. */
export const DOOR_NOTE: Record<"opened" | "closed" | "still recoverable", string> = {
  opened: "This is available to you now and was not at eighteen.",
  closed: "This one shut, or narrowed, somewhere in these years. Naming it is not the same as regretting it.",
  "still recoverable": "This went against you and it is not finished. Thirty is not a closing time.",
};
`;
fs.writeFileSync("content/sim/campaign/doors.ts", file, "utf8");
const counts = { opened: 0, closed: 0, "still recoverable": 0, skip: 0 };
for (const v of Object.values(merged)) counts[v.skip ? "skip" : v.state]++;
console.log(`content/sim/campaign/doors.ts: ${keys.length} flags — ${JSON.stringify(counts)}`);
